### ISSUE TITLE
Никнеймы админов

### ISSUE THREAD

**Issue by megowot** [SB-MaterialAdmin/Web#100]
Бесит что админы меняют свои никнеймы и когда нужно снять админку либо ещё что-то сделать то приходиться пользоваться поиском по steam Id.
Можно как то сделать чтобы в какое-то время сайт менял ники у админов.
**И ещё можно сделать как на faceit чтобы ник менялся у админа если не совпадал с бд**

**Comment by CrazyHackGUT** [comment]
Отдельным плагином лучше такое сделать.
Сделаю и на HLmod загружу.

**Comment by BlackYuzia** [comment]
Так есть же Такая дичь уже.
Admin Rename вроде

**Comment by CrazyHackGUT** [comment]
Это производит обратное действие: переименование админа на ник из БД.

**Comment by BlackYuzia** [comment]
Ну да. А разве @megowot не просит об этом?
@CrazyHackGUT Он же сказал что меняют ники, и хер найдешь.
Сделать что бы какой ник указал в БД такой и будет. А если сменит - меняется обратно.
это в AR есть...

**Comment by CrazyHackGUT** [comment]
@BlackYuzia он просит обратное, не тупи.
Чтобы если кто-то переименовался в Стиме, и зашёл на серв, то в БД СБ никнейм обновился.

**Comment by BlackYuzia** [comment]
О сорян. Я походу в Глаза долблюсь :D 
@CrazyHackGUT а разве это Рационально?
получается, что если ты Меняешь ник, то ты хер знает кто. 
К примеру:
Купил некий **Юзя** админку. (И создатель знает кто это)
а тут БАЦ, Орузя заходит на сервер и творит хуйню. 
Все пишут мол Орузя творит дичь, создатель не понимает КТО это ибо он никаким Орузям не продавал ничего.
А Орузя тем временем выходит, меняет ник, заходит обратно и все заебца. Мол он не виновен.
Смекаешь?

**Comment by CrazyHackGUT** [comment]
@BlackYuzia для этого в Стиме есть такая чудесная вещь, как "История изменения никнеймов пользователя".
Причём в окошке показываются точные даты изменения никнеймов, или короткие слова "Сегодня" или "Вчера".
Открывается всё это дело через список друзей:
![screen](https://i.imgur.com/7KPqloD.png)
![history](https://i.imgur.com/XDmgsic.png)

**Comment by BlackYuzia** [comment]
Орузя? Ах ты пидор.
Ну или Петух... :DD

**Comment by BlackYuzia** [comment]
Помимо этого, если у тебя 200+ админов на сервере, ты же не будешь идти и проверять каждого?

PS: Пираты ебали эту систему в зад.

**Comment by CrazyHackGUT** [comment]
В любом случае, есть логи сервера, где можно найти "неугодного админа" лишь по одному примерному нику и действию (CTRL + F -> "slapped").
Так что не вижу никаких проблем.
На крайняк логгировать действия админов в веб-лог.

**Comment by BlackYuzia** [comment]
Кстати. @CrazyHackGUT а где логи делись?
Раньше они были подробно и о каждом движении. (путь: addons/sourcemod/logs/admin(s))
а сейчас там тупо пусто... (но зато дохера логов в ../logs/materialadmin)

**Comment by CrazyHackGUT** [comment]
Подобных логов SourceBans/MaterialAdmin никогда не вёл.

**Comment by BlackYuzia** [comment]
Тогда что ведет? Сам SM?

**Comment by BlackYuzia** [comment]
PS: не проще общаться в Телеге а не тут?

**Comment by CrazyHackGUT** [comment]
Перенесено.
