### ISSUE TITLE
Ошибка перевода 

### ISSUE THREAD

**Issue by doctorweb44** [SB-MaterialAdmin/Web#114]
![image](https://user-images.githubusercontent.com/30326856/33424554-020ff984-d5de-11e7-9eff-8f8b5f70246f.png)
При попытке послать сообщение игроку, выскакивает окно, где написано ввеите вместо введите

**Comment by CrazyHackGUT** [comment]
Забавно. Почему-то GitHub об этом обсуждении не уведомил.
В любом случае, под такие косяки есть отдельный Issue #38
