### ISSUE TITLE
Class 'MaterialAdmin\DataStorage' not found

### ISSUE THREAD

**Issue by Nix1304** [SB-MaterialAdmin/Web#119]
При установке последней версии, такая ошибка после ввода данных администратора.
Fatal error: Class 'MaterialAdmin\DataStorage' not found in ......../install/template/page.5.php on line 95

**Comment by CrazyHackGUT** [comment]
Ну, как бы, ее ставить пока что не надо. Берем версию из релиза. Девелоперка делается, но медленно.

**Comment by Nix1304** [comment]
Версию 1.1.5.4 не надо?

**Comment by Nix1304** [comment]
Я не от туда скачивал
