### ISSUE TITLE
 Error: Class MaterialAdmin\DataStorage not found

### ISSUE THREAD

**Issue by tibehrius** [SB-MaterialAdmin/Web#120]
I'm trying to do a new installation, but I'm getting the following error in the last step:

https://prnt.sc/hy0pkj

Does anyone know what can it be?

**Comment by Meowmurmur** [comment]
#119

**Comment by tibehrius** [comment]
It is closed, and there was no solution. I can not finish the installation. = /

**Comment by Meowmurmur** [comment]
Developer's version is not fully completed yet and is done very slowly. @CrazyHackGUT not recommend to install dev-version.
(P.S. Google Translate :D)

**Comment by CrazyHackGUT** [comment]
I'll fix dev version tomorrow. Now i'm busy :/

**Comment by tibehrius** [comment]
Ok, thanks! ;)
