### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by mrstarkgame** [SB-MaterialAdmin/Web#127]
Критическая ошибка PHP
Произошла фатальная ошибка PHP Class 'MaterialAdmin\DataStorage' not found .../pages/header.php::111

**Comment by CrazyHackGUT** [comment]
Копия уже существующего обсуждения: #120 #119 
Ближе к вечеру уже поправлю.
А вообще, используйте релиз, он нормально работает. [Тык](https://github.com/SB-MaterialAdmin/Web/archive/release_1154.zip).
