### ISSUE TITLE
Информация о бане (VAC)

### ISSUE THREAD

**Issue by ruskydubl** [SB-MaterialAdmin/Web#133]
Добавить информацию о наличии Vac бана в дополнительной информации игрока который в был/есть в бан листе

**Comment by BlackYuzia** [comment]
Тут уже надо лепить модуль на "проверку VAC".
ну или пару строк кода...

А вообще. Если на сервере есть пираты. То людей с VAC-ом. Даже не пустит. RevEmu блочит всех с Вакейшеном...

**Comment by CrazyHackGUT** [comment]
@BlackYuzia так чисто выводить же в вебе.

**Comment by BlackYuzia** [comment]
@CrazyHackGUT ну по теме да.... но нахой? :C

**Comment by e-zhuravlev** [comment]
лучше сделать скрипт на удаление уже из бана тех кто с ваком) (Окунь уже кинул мне)
