### ISSUE TITLE
Вход через стим [Material Admin]

### ISSUE THREAD

**Issue by gastirt** [SB-MaterialAdmin/Web#135]
Добрый день. Раньше всё прекрасно и все администраторы могли войти через стим, но потом, по непонятным мне причинам, резко эта возможность перестала работать. Почему-то когда подтверждаешь вход через сам сайт стима, тебя кидает на сайт сурсбана и ничего не происходит. Steam API пробовал поменять. В чём может быть проблема?

**Comment by megoRU** [comment]
Может ты новый ключ не вписал к конфиг?

**Comment by megoRU** [comment]
Скинь сайт

**Comment by gastirt** [comment]
http://epic.myarena.ru/index.php

**Comment by gastirt** [comment]
Вписал в конфиг нвоый ключ

**Comment by gastirt** [comment]
на хлмоде тоже кто-то писал об этом) У вас всё нормально работает?

**Comment by megoRU** [comment]
Версия 1.1.5.4 (1) у тебя версия старая сайта обнови на новую. Но там будет большая ебля с папками. Ибо он поменял расположение)
у меня уже Версия 1.1.5.4 (520)

**Comment by CrazyHackGUT** [comment]
Да ёпт твою мать.
Сложно посмотреть один сраный коммит и внести правки?
https://github.com/SB-MaterialAdmin/Web/commit/a2bff2d628660ba5eb2453e284d710a568cb4ab7

Авторизацию Валв нагнули. Спасибо им.

**Comment by megoRU** [comment]
ну я был прав вообщем... @gastirt

**Comment by gastirt** [comment]
Спасибо за быстрый ответ
