### ISSUE TITLE
Плохой плагин

### ISSUE THREAD

**Issue by kanekisn** [SB-MaterialAdmin/Web#139]
Очень плохой сайт.

**Comment by kanekisn** [comment]
Не советую использовать.

**Comment by kanekisn** [comment]
Много багов

**Comment by Alexbu444** [comment]
Ты на плагин не гони.

**Comment by kanekisn** [comment]
Плохой дизайн

**Comment by Alexbu444** [comment]
Это да

**Comment by kanekisn** [comment]
Постоянно сыпит ошибки, а автор не хочет исправлять.

**Comment by megoRU** [comment]
Какой Пых?

**Comment by kanekisn** [comment]
5.6 версия

**Comment by BlackYuzia** [comment]
MA govno :1st_place_medal: 
@CrazyHackGUT :yoba:

**Comment by kanekisn** [comment]
@CrazyHackGUT - вот он, самый плохой кодер которого я видел.

**Comment by BlackYuzia** [comment]
Я чет орнул. @Alexbu444 пошли стебать Крузю.

**Comment by CrazyHackGUT** [comment]
Вы мне Гитхаб решили засрать коллективно? 
Чтобы этого обсуждения не было в течение суток. И мне глубоко насрать, что Гитхаб удалять их не дает. Как хотите, но удаляйте.
