### ISSUE TITLE
VAC Status not work?

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#143]
@CrazyHackGUT 
Статус в SB о VAC Бане сообщает нам что у данного игрока (Петрович) Vac "Отсутствует".
Смотря на его профиль в STEAM, SB идет нахер. Бикоз - у него **ВАК**.

![2018-05-12_105205](https://user-images.githubusercontent.com/25010528/39955109-a48ee430-55d2-11e8-85f4-0347ba512380.png)
![2018-05-12_105213](https://user-images.githubusercontent.com/25010528/39955108-a47071e4-55d2-11e8-8a1b-1e4c29535591.png)

**Comment by CrazyHackGUT** [comment]
Ключ-то прописан? API возвращает инфу, что бан есть.
![img](https://i.imgur.com/yW4ZLEP.png)

**Comment by BlackYuzia** [comment]
@CrazyHackGUT может лучше сделать так (см. скриншоты)
А то, "отсутствует" и "в наличии" как-то не очень красиво.

![2018-05-12_111201](https://user-images.githubusercontent.com/25010528/39955309-707a4e3e-55d5-11e8-8030-a010214d24bf.png)
![2018-05-12_111128](https://user-images.githubusercontent.com/25010528/39955310-70976316-55d5-11e8-85b2-8a19a4d62eca.png)

**Comment by CrazyHackGUT** [comment]
Цвета добавлю. Но менять текст не буду.
Ключ-то прописан

**Comment by BlackYuzia** [comment]
Ладно, думаю текст можно на изи сменить по своему усмотрению. (**кому надо - сменит**)
А что касательно ошибки?

**Comment by CrazyHackGUT** [comment]
Так ключ-то прописан? Ты мне ответишь сегодня наконец или нет?!

**Comment by CrazyHackGUT** [comment]
Окей, проблема подтвердилась. Вечером покурю этот код. Сейчас занят подготовкой к поездке в военком.
Интересно, почему изначально её не смог воспроизвести при разработке, хотя добавлял забаненных ваком.

**Comment by megoRU** [comment]
Ребята. Стим отключил api для просмотра банов. Я слашал об этом
http://www.vac-ban.com/?hl=ru
https://steamdb.info/stats/bans/

**Comment by CrazyHackGUT** [comment]
Не отключил, иначе я бы три часа назад не смог через браузер сделать запрос к API и узнать, есть бан или нет.

**Comment by megoRU** [comment]
ясно

**Comment by CrazyHackGUT** [comment]
This resolved already.
