### ISSUE TITLE
[BUG] Ваучеры сосут! | Vau4er suck!

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#147]
@CrazyHackGUT ля.. я не знаю как это описать. Просто ... посмотри на скрины.

> Активация ваучера нормального человека:

![2018-05-16_214130](https://user-images.githubusercontent.com/25010528/40137258-9fafc122-5952-11e8-9c97-429067b4b455.png)

> Активация ваучера Курильщика:

![2018-05-16_214109](https://user-images.githubusercontent.com/25010528/40137167-63709006-5952-11e8-9074-70e68717a204.png)

Ты мне объясни. Как можно было активировать ваучер так что бы ... запрос был почти полностью пуст? 
_ЧТО С ЭТИМ SB НЕ ТАК?_

**Comment by CrazyHackGUT** [comment]
Будешь и дальше злоупотреблять ренеймом темы - кину абуз. 
Строка запроса - GET-параметры. 
А то, что стек теряется - такое случается, если один из параметров содержит спец символ, который не может переварить ADOdb.

**Comment by CrazyHackGUT** [comment]
Завёл подобную #333. Эту закрываю.
