### ISSUE TITLE
Перестал работать бан группы 

### ISSUE THREAD

**Issue by e-zhuravlev** [SB-MaterialAdmin/Web#157]
Ввожу ссылку и причину (даже без причины) не банит
![sbgrban](https://user-images.githubusercontent.com/35569496/40835958-b89ff2f4-659d-11e8-9f90-5e19c407e624.jpg)

**Comment by CrazyHackGUT** [comment]
Сразу видно, кто не читает форум.
Эта проблема связана с массовым переходом Steam на HTTPS, и не только.
О ней известно.
