### ISSUE TITLE
Old de_dust 2 photo

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#166]
https://yadi.sk/i/vp6byOXs3Y37Pb new photo
![1212](https://user-images.githubusercontent.com/23276305/42735522-5e1326ba-885e-11e8-8d69-6a638d98d540.png)

**Comment by CrazyHackGUT** [comment]
Чёрт... Случайно часть файлов тоже полетела в коммит... Ладно, придётся откатывать коммит.
