### ISSUE TITLE
[Bug] Don't any change in Side Menu (Buttons)

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#171]
**Describe the bug**
Пытался немного изменить ccылку в боковом меню.
После изменения ссылки ... ничего не поменялось.
Пришлось создавать еще один пункт,

Баг или Фича?
**Expected behavior**
Ожидал, что сменится ссылка. (вот это поворот)
**Screenshots**
![image](https://user-images.githubusercontent.com/25010528/44622126-50a2d700-a8bb-11e8-9dab-b5462b2edf92.png)

**Comment by CrazyHackGUT** [comment]
Проблема подтвердилась. Взял в работу.

**Comment by BlackYuzia** [comment]
@CrazyHackGUT unban. pls.

**Comment by megoRU** [comment]
я хотел тоже сообщить об этом баге но забыл. + вообще пропал заголовок после изменения ссылки и все тупо слетело....

**Comment by BlackYuzia** [comment]
@megoRu Пропадает заголовок только тогда, когда в заголовке есть скобки (") если одиночные (') то все норм.

**Comment by CrazyHackGUT** [comment]
Проверьте теперь. Должно быть исправлено.
