### ISSUE TITLE
English translate

### ISSUE THREAD

**Issue by shadowDV** [SB-MaterialAdmin/Web#174]
hey,
 the Sourcebans is looking nice but I can't use it because it's on Russian there is any English translate that I can use? 
Regards

**Comment by CrazyHackGUT** [comment]
Hey.
We have in plans translation system, but for implementing, we need:
- Migrate from Smarty to Twig (_more, flexible template system_).
- Migrate from XAJAX to AJAX (_browser should receive only data, without HTML code_). This step also fix `XAJAX Error` when you send RCON commands, by example.
- Implement something for storaging phrases and languages. I like how it is done in XenForo. Maybe implement something similar?
- **ADOdb should be removed**. This is buggy library.

And yes, we need something for detect user browser language. We need search something for resolving this question.

Also, this is duplicate #111, so i should close this issue.
But you can still write questions here. I'll try write replies for all your questions.

_Yours faithfully, Sergey._

**Comment by shadowDV** [comment]
thank you! 
I will follow your project, for now, I will use the default sourceban because I can't find any other good template or design for sourceban

**Comment by shadowDV** [comment]
if i will translate the sourcecode from ru to en  its will work  ? like how other did it ?

**Comment by CrazyHackGUT** [comment]
Yes, this should work.
