### ISSUE TITLE
Часовой пояс

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/Web#176]
Как я только не менял часовой пояс в настройках он всегда остаётся не измененным в мутах и банах. На три часа он почему-то постоянно отстает хоть какой пояс ставь он будет постоянно на -3 часа назад.

**Comment by megoRU** [comment]
это не баг а фича. я вроде уже спрашивал. Но это не точно

**Comment by IIIef** [comment]
Какая фича?

**Comment by IIIef** [comment]
![img-2018-09-02-00-43-55](https://user-images.githubusercontent.com/13619790/44950157-5ebb9f00-ae49-11e8-95d9-fe2569307ff2.png)
![img-2018-09-02-00-44-09](https://user-images.githubusercontent.com/13619790/44950158-6418e980-ae49-11e8-9016-e825640c0df6.png)

**Comment by IIIef** [comment]
Разницу видим?

**Comment by IIIef** [comment]
Не в dev версии с часовым поясом проблем нет!

**Comment by megoRU** [comment]
я наверное тупой а где взять dev версию...

**Comment by IIIef** [comment]
https://github.com/SB-MaterialAdmin/Web.git

**Comment by megoRU** [comment]
значит у меня стоит дев версия по твоей логике но у меня разница в 3ч есть

**Comment by IIIef** [comment]
Ох емае, зайди в настройки и измени часовой пояс на любой, а потом посмотри измениться ли время выданного тобой бана или мута.

**Comment by megoRU** [comment]
да ты прав. но я давно это знал ну и что? пусть фиксит)

**Comment by CrazyHackGUT** [comment]
Да, знаю, что сломал это. Сейчас вроде в UTC поясе отображается (Гринвич). К следующему коммиту попробую сделать нормально.

**Comment by IIIef** [comment]
Понял, спасибо.

**Comment by CrazyHackGUT** [comment]
Готово. Проверьте, пожалуйста.
@IIIef @megoRU

**Comment by megoRU** [comment]
Проверь через час

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/45926525-f0d83400-bf2b-11e8-8344-d65665a5fd8e.png)
![image](https://user-images.githubusercontent.com/23276305/45926527-fafa3280-bf2b-11e8-9fa4-3ab74717e46b.png)
Время спешит

**Comment by megoRU** [comment]
на 10 мин

**Comment by megoRU** [comment]
@CrazyHackGUT

**Comment by IIIef** [comment]
Спасибо, проблема решена.

**Comment by CrazyHackGUT** [comment]
> Время спешит

Это уже проблема в настройках веб-сервера. Время на тачке некорректно настроено, видимо. Ибо вся работа с часовыми поясами и временем происходит на уровне самого PHP-интерпретатора.

**Comment by megoRU** [comment]
понял спасибо за фикус
