### ISSUE TITLE
Использовать GC

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/Web#177]
В настройках включаю (Использовать GC) и после сохранения галка слетает как-будто я не включал.

**Comment by CrazyHackGUT** [comment]
Не верстальщик, к сожалению. Нид хелп, не пойму где собака зарыта.

**Comment by CrazyHackGUT** [comment]
Проверь сейчас. Вроде подправил.

**Comment by IIIef** [comment]
Да работает, спасибо.
