### ISSUE TITLE
Доступна новая версия

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#180]
![image](https://user-images.githubusercontent.com/23276305/45233089-53012a00-b2da-11e8-9ad2-67804491ad46.png)
![image](https://user-images.githubusercontent.com/23276305/45233100-5a283800-b2da-11e8-897e-08a8cb328cd8.png)
У меня стоят все обновы почему такое?

**Comment by CrazyHackGUT** [comment]
Потому что там идёт банальная сверка строки. Потому и думает, что есть обновы, ибо "ласт" отличается от установленной.
Информацию о последней версии берёт [отсюда](https://github.com/SB-MaterialAdmin/Web/blob/master/updates.json).

**Comment by megoRU** [comment]
Так че делать с этой ситуацией

**Comment by CrazyHackGUT** [comment]
Ничего. Просто игнорировать.

**Comment by megoRU** [comment]
Мой внутренний перфекционизм умер

**Comment by CrazyHackGUT** [comment]
Вырезал это вообще, потому и баг неактуален.
