### ISSUE TITLE
Не работает вывод ПОСЛЕДНИЙ ВИЗИТ

### ISSUE THREAD

**Issue by stotik** [SB-MaterialAdmin/Web#182]
При авторизации нет записи в бд о заходе на сайт. Колонка lastvisit имеет значение NULL постоянно.
DEV

**Comment by megoRU** [comment]
ахуенно 
![Uploading image.png…]()

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/45380629-cae99000-b60b-11e8-8693-4a66535096b9.png)
я поставил 1.1.5.4

**Comment by CrazyHackGUT** [comment]
PHP не может влиять на состояние соединения. Тут уже скорее либо хостинг, либо провайдер.

**Comment by megoRU** [comment]
это майарена тупая сломала себе все сори...
