### ISSUE TITLE
Вывести количество админов на каждом из серверов

### ISSUE THREAD

**Issue by stotik** [SB-MaterialAdmin/Web#183]
На странице "Админлист" В каждом из серверов есть никому не нужная, и не понятная для чего она там существует иконка. Так вот, вместо неё можно сделать вывод "количество админов" на каждом из серверов
![2](https://user-images.githubusercontent.com/42479404/45381075-f5881880-b60c-11e8-9b58-19a3cb7cbf9d.PNG)

**Comment by CrazyHackGUT** [comment]
Не вижу никакой проблемы это сделать.
Шаблонизатору кол-во администраторов уже передаётся. Просто практически нигде не используется, кроме как здесь:
https://github.com/SB-MaterialAdmin/Web/blob/6eebf6350be88d2aea11a4abf0c431e41a5ec90a/web_upload/theme/page_adminlist.tpl#L16-L18

Для вывода просто воткнуть что-то вроде такого в нужное место:
```html
{$server.admincount}
```

**Comment by stotik** [comment]
Понял. Закрывай)
