### ISSUE TITLE
[Bug] Vac Check Bot

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#186]
Кратко: Забанили бота, вак чек охерел.
Начал спамить ошибкой:

>Критическая ошибка PHP
Произошла фатальная ошибка PHP Uncaught InvalidArgumentException: Invalid SteamID passed. in /home/ххххххххх/public_html/includes/CSteamId.php:13 Stack trace: #0 /home/хххххх/public_html/includes/system-functions.php(1634): CSteamId::factory('BOT') #1 /home//хххххх/public_html/pages/page.banlist.php(559): GetVACStatus('BOT') #2 /home/хххххх/public_html/includes/page-builder.php(143): include('/home/ххххх...')
Ххххх/index.php(35): include_once('/home/ххххх...') #4 {main} thrown /home/хххххх/public_html/includes/CSteamId.php::13

Желательно добавить проверку на бота.

**Comment by megoRU** [comment]
хахахха

**Comment by megoRU** [comment]
f
