### ISSUE TITLE
[REQ] "Чтение" ссылок в причине бана/разбана 

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#190]
@CrazyHackGUT есть идея касательно "причины бана/разбана".

Есть ли возможность сделать проверку причины бана/разбана на наличие ссылок (аля детект `http://` и `https://`) и, если они (ссылки) есть в причине бана то делать их кликабельными, т.е. возможность переходить по ссылке.? :thinking: 

Вот как сейчас, бывает иногда нужно влепить ссылку в причины бана (например, было обсуждение на форуме, и вердикт: **Банан**):
![image](https://user-images.githubusercontent.com/25010528/46345434-3cd25980-c64d-11e8-8a1b-24d0cc252e2f.png)

**Comment by CrazyHackGUT** [comment]
Возможно всё. Чуть позже посмотрю, как это реализовано в том же XenForo, т.к. не уверен в простоте логики подобной хрени.

**Comment by CrazyHackGUT** [comment]
https://material.kruzya.me/index.php?p=banlist&searchText=STEAM_0%3A0%3A55665612
Тут можно посмотреть.
