### ISSUE TITLE
Русский язык

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#191]
![image](https://user-images.githubusercontent.com/23276305/46417201-ca877500-c731-11e8-88de-a1d8c475f14a.png)
8 часов мб не? Ну если 1 час то да верно, но 2 часа и так далее)

**Comment by baferpro** [comment]
Легче сделать "N ч."
А то так надо на каждый из 24 часов проверку делать и собственно к ним свои падежи.

**Comment by megoRU** [comment]
это пусть он решает как лучше

**Comment by CrazyHackGUT** [comment]
Лучше сократить, всё же, время.
Склонение этих "часов" и тд - довольно морочная задача.
