### ISSUE TITLE
Не работает (пожаловаться на игрока)

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/Web#192]
Заметил пару багов, один сейчас опишу, когда нажимаю на кнопку пожаловаться на игрока, то выходит пустое окно с надписью
![img-2018-10-03-20-26-37](https://user-images.githubusercontent.com/13619790/46427932-53f77100-c74b-11e8-86b6-7ecafd6270bf.png)
![img-2018-10-03-20-25-57](https://user-images.githubusercontent.com/13619790/46427939-58238e80-c74b-11e8-883d-faa9e62da8a1.png)

 пожаловаться на игрока и все на этом замирает)

**Comment by CrazyHackGUT** [comment]
Не подтверждаю. Всё работает корректно.
![default](https://user-images.githubusercontent.com/12576822/46532808-7ad0b700-c8b3-11e8-9c28-d6cb8a1ae329.png)
Нужно больше деталей.

**Comment by BlackYuzia** [comment]
Отмазка из разряда "А у меня все работает"? :D

**Comment by CrazyHackGUT** [comment]
Не отмазка, а утверждение.
Белый экран будет только если "Пожаловаться на игрока" не полностью включено.
Например, когда включен пункт, а сама страница в настройках SB - нет.

**Comment by IIIef** [comment]
Хорошо, переустановлю с нуля и проверю и да забыл написать, это на dev версии.

**Comment by CrazyHackGUT** [comment]
Кадр выше сделан как раз на dev-версии.

**Comment by IIIef** [comment]
С нуля поставил и ничего не изменилось. Когда в настройках отключена эта функция,
![img-2018-10-06-19-36-19](https://user-images.githubusercontent.com/13619790/46573570-db3d2280-c99f-11e8-9789-3f7bbfbcf314.png)
![img-2018-10-06-19-36-40](https://user-images.githubusercontent.com/13619790/46573571-db3d2280-c99f-11e8-8b65-a921485b1158.png)
![img-2018-10-06-19-37-16](https://user-images.githubusercontent.com/13619790/46573572-db3d2280-c99f-11e8-90e6-ea76ef2f6e48.png)


 тогда выдает ошибку, а так вроде все включено и на странице глухо все.

**Comment by CrazyHackGUT** [comment]
Можно ссылку на СБ? Если публично не хотите, отправьте на E-Mail feedback@kruzya.me с темой `GitHub SB Issue #192`

**Comment by IIIef** [comment]
http://46.151.24.134/idle/tect

php 5.5

**Comment by IIIef** [comment]
Есть решение проблемы?

**Comment by CrazyHackGUT** [comment]
Есть возможность предоставить доступ к серверу с сайтом? Что-то мне подсказывает, что там ошибка вылезает у Вас какая-то.

**Comment by IIIef** [comment]
Ошибок нет все чисто в логах, стоит Open Server.

**Comment by CrazyHackGUT** [comment]
Покажите настройки модулей в таком случае (активированные версии веб-сервера, PHP, MySQL). Попробую воспроизвести.

**Comment by IIIef** [comment]
Эти настройки интересуют?
![img-2018-10-30-09-19-02](https://user-images.githubusercontent.com/13619790/47699739-f577c280-dc24-11e8-9a78-040027bb7c76.png)

**Comment by CrazyHackGUT** [comment]
Проверю в течение двух-трёх часов.
Да, эти.

**Comment by CrazyHackGUT** [comment]
Проверьте сейчас.
Непонятно только, почему эта проблема не вылезает на 5.6 и 7.х

**Comment by IIIef** [comment]
Спасибо, теперь все работает.
