### ISSUE TITLE
Не знаю, как решить проблему с updater.

### ISSUE THREAD

**Issue by telox** [SB-MaterialAdmin/Web#193]
Во время перехода на страницу updater
В файле Database.php on line 123 
Изменял 
    $user     = $config['user(Тут ставил логин и пароль от веб части и от БД. Ничего не помогло.)'];
    $pass     = $config['pass'];

An exception occured: [PDOException] SQLSTATE[28000] [1045] Access denied for user 'sourcebans'@'46.174.49.3' (using password: YES) in /includes/classes/Database.php on line 123 
PDO->__construct(string, string, string, array) in /includes/classes/Database.php at line 123
Database->Connect(array) in /includes/classes/Database.php at line 9
Database->__construct(array) in /includes/classes/DatabaseManager.php at line 30
DatabaseManager::InitConnection(string) in /includes/classes/DatabaseManager.php at line 16
DatabaseManager::GetConnection() in /init.php at line 262
include(string) in /updater/index.php at line 74

**Comment by CrazyHackGUT** [comment]
Неоднократно обсуждалось на HLmod в официальной теме.
Необходимо удалить `data/db.php` перед обновлением.

Попробуйте и отпишитесь.

**Comment by telox** [comment]
Благодарю. Почему-то гугл не выдает запрос с hlmod с соотвествующему запросу.

**Comment by telox** [comment]
Установилось. Обновилось. 
Ставлю с myarena. Теперь при авторизации выдаёт окно уведомления 
server returned Http 500 
Критическая ошибка php

**Comment by hirowatch** [comment]
Молодец Dev версия не поддерживает ПЫХ 5.4

**Comment by telox** [comment]
> Молодец Dev версия не поддерживает ПЫХ 5.4
Где же тогда stable взять?

**Comment by telox** [comment]
Нашёл на форуме арены. Спасибо большое.

**Comment by CrazyHackGUT** [comment]
> Где же тогда stable взять?

Действительно, где...
![default](https://user-images.githubusercontent.com/12576822/46912780-35397b80-cf90-11e8-8a00-52f68bcc944b.png)
