### ISSUE TITLE
неправильные данные и ссылка не работает

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#195]
/theme_link (при нажатии на ПОДДЕРЖКА)
И еще чет версия странная буквенная
![image](https://user-images.githubusercontent.com/23276305/47174985-d0c54600-d31a-11e8-94b3-a80d0396429c.png)

**Comment by hirowatch** [comment]
О проблеме уже известно.
Дальнейшее обновление будет со стороны @CrazyHackGUT
