### ISSUE TITLE
ошибка 500

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#202]
![image](https://user-images.githubusercontent.com/23276305/47966558-ddf56b00-e064-11e8-9779-8b4f39f1712e.png)
Хостинг майарена)
Но сказали что это не у них проблемс

**Comment by CrazyHackGUT** [comment]
Сб такие короткие сообщения о коде 500 не генерирует, да еще и без стилей. Это веб сервер у Арены скорее.
