### ISSUE TITLE
Ваучеры HELP!

### ISSUE THREAD

**Issue by SkiFteL** [SB-MaterialAdmin/Web#203]
При создании ваучера выдает ошибку!
В БД данные строки есть, но в шаблоне MA нет кода...
Где найти данный файл с правками!? Спасибо заранее...

`[256] mysqli error: [1048: Column 'pcode' cannot be null] in EXECUTE("INSERT INTO `sb_vay4er` (`activ`, `value`, `days`, `group_web`, `group_srv`, `servers`, `pcode`, `pwd`) VALUES (1, '4704165772412017', '55', 'Зам. Гл.Админа WEB', 'Супер Админ', ',s1', NULL, NULL)") 
Произошла фатальная ошибка на строке 79 в файле /mnt/iscsi/www/bond/data/www/мой-сайт.ру/sb/includes/adodb/adodb-errorhandler.inc.php
`

Проблема с строками в БД **pcode** и **pwd**
Данных нет в шаблоне темы MA

**Comment by CrazyHackGUT** [comment]
А откуда у Вас вообще эти колонки в БД? Их нет в оригинале:
![default](https://user-images.githubusercontent.com/12576822/48976390-13a7d580-f0a0-11e8-9552-60dff624ddad.png)

**Comment by SkiFteL** [comment]
Там при создании ваучера было
Колонка когда создаёшь ваучер там было поле "Поставить галочку" защита стим ид!
А при активации Ваучера должно быть поле для ввода "сервер пароль"
Вот этого щас нет в файле шаблона - так как дизайнер заменил на стандартные файлы...

**Comment by CrazyHackGUT** [comment]
> Колонка когда создаёшь ваучер там было поле "Поставить галочку" защита стим ид!

Этого в этом SB никогда не было.
Обращайтесь к тому, кто устанавливал.
