### ISSUE TITLE
SKIN {ID} chat message spam + просадка FPS 

### ISSUE THREAD

**Issue by Fayozjon** [SB-MaterialAdmin/Web#207]
**Describe the bug**
При активации плагина сильно падает фпс + начинается спамится слова SKIN 133 SKIN 412 ....
в чате.

![image](https://user-images.githubusercontent.com/9584679/50080438-e4533700-020d-11e9-84e9-07e93f4c614f.png)

Список установленных плагинов:
```
sm plugins list
[SM] Listing 31 plugins:
  01 "Sound Commands" (1.9.0.6269) by AlliedModders LLC
  02 "Player Commands" (1.9.0.6269) by AlliedModders LLC
  03 "Map configs" (1.3) by Berni
  04 "Client Preferences" (1.9.0.6269) by AlliedModders LLC
  05 "Only Headshot" (2.0.2) by Bara
  06 "Resetscore+" (1.5.1) by AlmazON
  07 "No Prime Manager" (1.0.0) by OkyHp
  08 "Reserved Slots" (1.9.0.6269) by AlliedModders LLC
  09 "Advanced Admin ESP" (1.3.5) by Mitch
  10 "SourceMod Anti-Cheat" (0.8.6.0) by SMAC Development Team
  11 "Admin all spec" (1.0.2) by Dr!fter
  12 "autodemo" (2.3.1) by mukunda
  13 "Реклама" (1.4) by Pheonix (˙·٠●Феникс●٠·˙)
  14 "Easy Restart Game" (1.0) by KryptoNite[IL]
  15 "RankMe" (3.0.3.Kento.30.2) by lok1, Scooby, Kento, pracc, Kxnrl, CrazyHackGUT
  16 "Basic Votes" (1.9.0.6269) by AlliedModders LLC
  17 "Basic Chat" (1.9.0.6269) by AlliedModders LLC
  18 "Material Admin" (0.7.7) by Material Admin Dev Team
  19 "SMAC Aimbot Detector" (0.8.6.0) by SMAC Development Team
  20 "Fun Votes" (1.9.0.6269) by AlliedModders LLC
  21 "Admin Help" (1.9.0.6269) by AlliedModders LLC
  22 "AFK Manager" (4.2.2) by Rothgar
  23 "Admin Menu" (1.9.0.6269) by AlliedModders LLC
  24 "Admin File Reader" (1.9.0.6269) by AlliedModders LLC
  25 "SM File/Folder Downloader and Precacher" (1.4) by SWAT_88
  26 "Basic Info Triggers" (1.9.0.6269) by AlliedModders LLC
  27 "Fun Commands" (1.9.0.6269) by AlliedModders LLC
  28 "Basic Comm Control" (0.7.7) by AlliedModders LLC
  29 "Basic Commands" (1.9.0.6269) by AlliedModders LLC
  30 "Anti-Flood" (1.9.0.6269) by AlliedModders LLC
  31 "High Ping Kicker" (2.9) by Liam
```

P,S:
Наблюдается такое в обеих версиях 
Oldserver
Newserver

**Comment by BlackYuzia** [comment]
Не нашел на скрине слов + ма может конфликтовать с каким либо плагином который эти сообщения выводит.

**Comment by Fayozjon** [comment]
Плагин со скинами стоит на сервере рядом. Может ли быть такой конфликт?

**Comment by Grey-rus** [comment]
Это не наш плагин спамит, ищи другой.

**Comment by CrazyHackGUT** [comment]
Плагины таким не спамят.
Проверяется очень легко. Открываем поиск, пишем `Skin`, удивляемся: ничего не найдено.
[Поиск по коду нового плагина](https://github.com/SB-MaterialAdmin/NewServer/search?q=Skin&unscoped_q=Skin) и, соответственно, [поиск по коду старого плагина](https://github.com/SB-MaterialAdmin/OldServer/search?q=Skin&unscoped_q=Skin)

**Comment by STiNG645** [comment]
Мы перепроверили, надпись выходит только когда ваш плагин включен. Иначе мы бы здесь не писали. Я могу предоставить видео, если хотите.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/50164239-2904ce00-02f3-11e9-9837-51d0faac88f5.png)

**Comment by CrazyHackGUT** [comment]
Вы уверены, что это делает именно наш плагин?
Ради чистоты эксперимента, выгрузите все остальные  плагины, оставьте только MA в рабочем состоянии.

**Comment by Fayozjon** [comment]
Reinstalled
