### ISSUE TITLE
Пустая страница

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#208]
/index.php?p=admin&c=servers&o=dbsetup
![image](https://user-images.githubusercontent.com/23276305/50182934-b6f7ad80-0321-11e9-9c4c-179502010a80.png)
Ничего
![image](https://user-images.githubusercontent.com/23276305/50182945-bf4fe880-0321-11e9-9289-f03ff3bccd09.png)

**Comment by CrazyHackGUT** [comment]
Не полностью страничку вырезали...
https://github.com/SB-MaterialAdmin/Web/commit/5b6b2fe440fc100e69a33303c5ffa4800566e56f

**Comment by hirowatch** [comment]
А зачем ее вырезали? Или она была перенесена?

**Comment by CrazyHackGUT** [comment]
Потому что это дырка в безопасности.
Представьте, что будет, если у администратора, у которого есть доступ к полному управлению серверов, но нет остальных прав.
Он сможет получить данные от БД, и если он чисто случайно он найдёт на домене с СБ phpMyAdmin, то сможет "пошалить".

**Comment by megoRU** [comment]
орнул ну крч закрывай

**Comment by CrazyHackGUT** [comment]
Наличие ссылки на эту страницу - баг.
Как только уберу её (планирую сегодня) - закрою.
