### ISSUE TITLE
GeoIP 504

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#213]
Крч на майарене на последнем пыхе 7.2 при обновлении GeoIP -сайт. Удачи в тестировании.
![image](https://user-images.githubusercontent.com/23276305/51139424-e7fdcc00-1854-11e9-87eb-943cc25d4907.png)
Тут смерть:
![image](https://user-images.githubusercontent.com/23276305/51139434-f1873400-1854-11e9-8c6c-d8bb42484735.png)

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/51139554-4460eb80-1855-11e9-83f0-ad04a16d8fdc.png)
и кстати теперь вот так)(

**Comment by megoRU** [comment]
@CrazyHackGUT 
![image](https://user-images.githubusercontent.com/23276305/51196440-2f8d6200-1900-11e9-9080-d8e9c49564bc.png)
Но не у всех
![image](https://user-images.githubusercontent.com/23276305/51196466-3ae08d80-1900-11e9-8fd3-dc9612ea3ca6.png)

**Comment by CrazyHackGUT** [comment]
После обновления БД, надо выполнить перестроение или сброс GeoIP кеша. Делается там же.

**Comment by megoRU** [comment]
я не понял.

**Comment by CrazyHackGUT** [comment]
![default](https://user-images.githubusercontent.com/12576822/51263470-be1be500-19cd-11e9-95fb-81541eca114c.png)
Что-то одно запустите.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/51264321-4b0f7000-19c7-11e9-92f4-b62f783752bf.png)
-майарена)

**Comment by CrazyHackGUT** [comment]
Скорее всего обновление запустили, так?
Это довольно ресурсоёмкий по времени процесс. Скорее всего в лимит времени упёрлись.

**Comment by megoRU** [comment]
я нажал то что нижнее вы выделили

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/51353628-3794ff80-1ac2-11e9-915b-efaed7282cca.png)
все равно. Я поставил 300 секунд (прошло примерно 30 сек)
![image](https://user-images.githubusercontent.com/23276305/51353651-48457580-1ac2-11e9-85fb-0ae1bb76825a.png)
