### ISSUE TITLE
Слетел сайт?)

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#220]
Не этот ли коммит натворил такое?

https://github.com/SB-MaterialAdmin/Web/commit/67a4ba4226ea45fd8b817d87ea835913306e5506

![image](https://user-images.githubusercontent.com/23276305/54551282-dc4a9500-49be-11e9-865e-be95c15db99f.png)

**Comment by CrazyHackGUT** [comment]
Браузер? На Firefox не воспроизводится:
![изображение](https://user-images.githubusercontent.com/12576822/54582424-1bfa9680-4a2a-11e9-9266-d0ea59ffdbf1.png)

**Comment by megoRU** [comment]
![Screenshot_2019-03-19-11-55-01-661_com android chrome](https://user-images.githubusercontent.com/23276305/54592711-fd05ff80-4a3d-11e9-8fde-8da9902e7e3d.png)


На ПК у меня chrome canary. Не спрашивай почему использую так надо.....

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/54596903-a3ee9980-4a46-11e9-8a60-c602f397856d.png)
это на chrome beta.))) ясно че не так с canary
@CrazyHackGUT

**Comment by CrazyHackGUT** [comment]
На Канарейке последней тоже не удаётся воспроизвести...
![страница](https://user-images.githubusercontent.com/12576822/54705576-96283980-4b56-11e9-9a6c-f325e47506f1.png)
![версия](https://user-images.githubusercontent.com/12576822/54705593-9f190b00-4b56-11e9-8ba6-a7da8ccc2aad.png)

**Comment by CrazyHackGUT** [comment]
Закрываю, в связи с невозможностью воспроизвести на последней версии браузера. Могу предложить лишь попробовать обновить браузер на компьютере.
