### ISSUE TITLE
An exception occured: [PDOException] SQLSTATE[28000] [1045] Access denied for user 'sourcebans'@'localhost' (using password: YES) in /includes/classes/Database.php on line 123

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#221]
![image](https://user-images.githubusercontent.com/23276305/54708303-2add6800-4b54-11e9-9f3c-92a1d785906e.png)

в чем проблема?

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/54708863-59a80e00-4b55-11e9-9cfd-ad2114e615e3.png)
в процессе установки...

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/54708905-73e1ec00-4b55-11e9-9807-e781932c6c88.png)
в процессе установки

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/54709407-7b55c500-4b56-11e9-849f-287bc6bfc2d0.png)
ПРОГРЕСС!!!

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/54711527-354f3000-4b5b-11e9-9f57-b9e2c6b86d3e.png)

**Comment by megoRU** [comment]
крч одно я понял. либо я даун либо оно не устанавливается.

**Comment by megoRU** [comment]
либо дайте инструкцию.... (200 iq)

**Comment by CrazyHackGUT** [comment]
Файл `data/db.php` удали, после запусти апдейтер.

**Comment by megoRU** [comment]
тогда сайт вообще пустой ничего нет на updater

**Comment by megoRU** [comment]
ясно.

**Comment by megoRU** [comment]
как кеш аватарок исправить?

**Comment by megoRU** [comment]
я их пересобрал и очистил но чет не появились

**Comment by megoRU** [comment]
@CrazyHackGUT крч проблема решена. Но пересмотри установку SB ппц конечно муторно. Зачем такие сложности....

**Comment by CrazyHackGUT** [comment]
Это девелоперка. А установщик в любом случае переделываться будет.
