### ISSUE TITLE
Class 'Locale' not found

### ISSUE THREAD

**Issue by MAGNAT2645** [SB-MaterialAdmin/Web#223]
Решил попробовать dev версию из master-ветки, потому что с версией из последнего релиза появились странные баги при выдаче Мут+Гаг (перестают блокировать текстовый чат, и иногда голосовой) через Веб.

При замене файлов из web_upload сначала была ошибка с подключением к БД, но я её как-то исправил (забыл уже), а тут пишет, что класс не найден. Я порылся в папках и не нашёл определения этого класса.

```
An exception occured: [Error] Class 'Locale' not found in /includes/Language.php on line 102

    Kruzya\Generic\Language->retrieveUserLanguage() in /includes/Language.php at line 80
    Kruzya\Generic\Language->addPhrasesToCache(string) in /includes/Language.php at line 67
    Kruzya\Generic\Language->retrieve(string, array) in /init.php at line 303
    include_once(string) in /index.php at line 37
```

P.S. Я не был уверен по поводу обновления через updater, потому что мне казалось, что это ничего не изменит. Поэтому попробовал установить вручную.

**Comment by MAGNAT2645** [comment]
Или может можно как-то отключить эту фичу с локализацией?

**Comment by MAGNAT2645** [comment]
Исправилось с помощью установки через install и последующие шаги в updater и т.д.
![изображение](https://user-images.githubusercontent.com/11666918/57623602-7f77ef00-75a9-11e9-9293-b1f1b1df0aa5.png)

**Comment by CrazyHackGUT** [comment]
Непонятно, как именно тут помогла установка и обновление базы данных, если `Locale` - стандартный класс самого PHP, и для его наличия должно быть установлено соответствующее расширение. Ну ладно.

**Comment by A1mDev** [comment]
Столкнулся с такой же проблемой. Исправляется установкой php intl.
Комманды для linux:
``` sudo apt-get install php-intl ```
``` sudo service apache2 restart ```
