### ISSUE TITLE
ваучер продления админ привилегии 

### ISSUE THREAD

**Issue by valeologist** [SB-MaterialAdmin/Web#227]
Есть ваучер активации админки, но нет возможности продлевать админку так же ваучером! То есть, если игрок хочет продлить админку - он не может этого сделать потому, что ему будет писать, что такой пользователь с таким стим айди зарегистрирован. Мне приходится продлевать админку самому!

**Comment by CrazyHackGUT** [comment]
Как вариант, вижу такое решение сложившейся ситуации.
Не отжимать доступ у админа в веб СБ. Вместо этого, при попытке зайти на страницу аккаунта/добавление бана/etc., выводить ему страницу, мол админка истекла с предложением продлить, и полем для ввода кода ваучера.

**Comment by valeologist** [comment]
самый идеальный вариант так сделай

**Comment by valeologist** [comment]
но есть ещё одно! если игрок продлевает админку, то он может захотеть другую группу,, то есть при продлении группа автоматически должна так же поменяться и серверная группа тоже. Реализуешь?

**Comment by CrazyHackGUT** [comment]
Реализую.

**Comment by BlackYuzia** [comment]
@CrazyHackGUT хрень вариант.
А если данный чел не зайдет в аккаунт?
Все, нельзя продлить? Не надо нам такой фигни.

Пусть вводит как обычно. А то там вводи что бы продлить, а там вводи что бы получить.
А не слишком ли сложно? Некоторые не знают что такое STEAMID вообще. А тут ты заставляешь еще думать куда и что им вводить. 

**PS: Сделай лучше ключи и вырежи Ваучеры нахой из СБ.**
**PSS: Ключи под приват. :eyes:**

**Comment by CrazyHackGUT** [comment]
> А если данный чел не зайдёт в аккаунт?

Мысль не ясна.

**Comment by BlackYuzia** [comment]
Поясняю. У тебя есть челик который НЕ заходит в акк.
(Ищет кнопку где он когда-то активировал ключ)
Тыкает туда. Вводит А ОНО НЕ БУМ-БУМ (ну понял да?)
Пишет владельцу сервера (или кто там ему этот недо-ключ выдал?)
И говорит мол ЧЕ ЗА ХРЕНЬ. Я ТУДА ВСТАВИЛ А ОНО НИЧЕГО. (Говорю. Так и скажет)
Ну а ты в недоумении (работать же должно. Проверял)
Создаешь ваучер (на продление), суешь куда надо (в аккаунте) у тебя все продлевает.
А он все равно говорит нет. В конечном итоге мы поймем что он НЕ там где надо вставлял.
НО это займет некоторое время.

**Comment by BlackYuzia** [comment]
Если уж и делать. То делать так что бы ВСЕ активировалось/продлевалось в одном и том же месте.
А не в разбой.

**Comment by CrazyHackGUT** [comment]
Юзеру всё равно придётся вводить логин или SteamID при продлении.

**Comment by valeologist** [comment]
@CrazyHackGUT Я ег оне могу поддержать потому, что он узко мыслит! ваучер можно сделать каки актьивацией, так и продлением с тем способом, который ты предлагал, но не каких двойных разделов, просто можно сделать проверку, если аккаунт существует, то предложитть продление ваучера, если аккаунта не существует, то активация

**Comment by valeologist** [comment]
> 
> 
> Юзеру всё равно придётся вводить логин или SteamID при продлении.

Я ег оне могу поддержать потому, что он узко мыслит! ваучер можно сделать каки актьивацией, так и продлением с тем способом, который ты предлагал, но не каких двойных разделов, просто можно сделать проверку, если аккаунт существует, то предложитть продление ваучера, если аккаунта не существует, то активация

**Comment by Septembers** [comment]
юзя тупой

**Comment by BlackYuzia** [comment]
> Юзеру всё равно придётся вводить логин или SteamID при продлении.

@CrazyHackGUT ключи лишены этого недостатка.

**Comment by xeeek** [comment]
Странно почему маленький приоритет, если эта функция самая необходимая на данный момент тем, кто использует ключи.

**Comment by xeeek** [comment]
Вот и прошёл еще 1 год ожидания ваучеров

**Comment by valeologist** [comment]
> 
> 
> Вот и прошёл еще 1 год ожидания ваучеров

Походу никогда не будет ваучер продление.

**Comment by e-zhuravlev** [comment]
> > Вот и прошёл еще 1 год ожидания ваучеров
> 
> Походу никогда не будет ваучер продление.

Проще уже свое сделать чем ждать фиксы в этой дыре))

**Comment by CrazyHackGUT** [comment]
Дубликат #49, дальнейшие изменения будут вноситься по нему.
