### ISSUE TITLE
Установите права 777 на папку через FTP-клиент.

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#230]
/bans/data/theme_c/ не перезаписываемая! Установите права 777 на папку через FTP-клиент.

Я выдал. Но ничего не поменялось

**Comment by hirowatch** [comment]
Попробуй 755

**Comment by CrazyHackGUT** [comment]
А права точно выдались? На ту папку хоть выдаёте?

**Comment by megoRU** [comment]
Починил.
