### ISSUE TITLE
В чем проблема

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#235]
![image](https://user-images.githubusercontent.com/23276305/61583501-6eb39e80-ab41-11e9-856d-e0ffeacac3eb.png)
**theme_c/** 
с этой папкой что то творится и на сайте все пропадает. Но если там очистить то все появляется
.
![image](https://user-images.githubusercontent.com/23276305/61583508-8723b900-ab41-11e9-88a8-c1079b5bb87e.png)
.
![image](https://user-images.githubusercontent.com/23276305/61583510-8db23080-ab41-11e9-9fc4-93cbaa6849ec.png)

**Comment by CrazyHackGUT** [comment]
Папка - кеш шаблонизатора.
Шаблонизатор - проект, никак не связанный с СБ. Вопрос надо задавать разработчикам Smarty (ответят навряд ли, ибо используется версия, которая уже не поддерживается ими официально), или хостингу. Просто так СБ эту папку не чистит и не трогает.
