### ISSUE TITLE
Удаление истёкших админов.

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/Web#237]
Решил удалить истекших админов, а они не удаляются через обслуживание системы. 
![img-2019-07-23-21-03-39](https://user-images.githubusercontent.com/13619790/61736350-8fbcff00-ad8e-11e9-8532-8251952c6611.png)
Пишет, что удаленно, но обновив страницу, вижу всех истекших админов снова)))

**Comment by CrazyHackGUT** [comment]
Так удаляются, или нет?
На скриншоте отчётливо вижу "Успех".

**Comment by BlackYuzia** [comment]
ОРУ.

**Comment by IIIef** [comment]
> Так удаляются, или нет?
> На скриншоте отчётливо вижу "Успех".

Показывает, что успех, а по факту нет)))

**Comment by CrazyHackGUT** [comment]
Посмотрел код. Не пойму, как он вообще работал. Сейчас переделаю функцию, попрошу проверить.

**Comment by IIIef** [comment]
> Посмотрел код. Не пойму, как он вообще работал. Сейчас переделаю функцию, попрошу проверить.

Ок. спс)

**Comment by CrazyHackGUT** [comment]
Исправил.
https://github.com/SB-MaterialAdmin/Web/commit/c340da8fa2af953e3ce44005b64c93ad1f05b1c1
Проверьте.

**Comment by IIIef** [comment]
Спс, работает, а можно также быстро решить вот эту проблему? https://github.com/SB-MaterialAdmin/Web/issues/224#issuecomment-511218149 цена вопроса 500р.

**Comment by CrazyHackGUT** [comment]
Быстро не получится. Постараюсь на этой неделе решить.

**Comment by IIIef** [comment]
Хорошо, спс.
