### ISSUE TITLE
Неправильная иконка мода

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#239]
![image](https://user-images.githubusercontent.com/23276305/62006744-898f9f80-b14d-11e9-8af7-41e198c4959f.png)

Когда банишь через сайт `/index.php?p=admin&c=bans`

Вот такая фича... Он не знает какой мод.... Фиксбы

**Comment by CrazyHackGUT** [comment]
Видимо, иконку снесли.
Там веб-часть оформлена отдельным модом в базе. У него всегда ID - 0.
Проверьте наличие записи, и наличие указанного файла у неё.

**Comment by megoRU** [comment]
ну значит надо ее добавить. Да я видел там web что пнг вроде

**Comment by CrazyHackGUT** [comment]
Проверьте старые баны из веб-панели.
Нулевая запись в модах не трогается ни установщиком, ни апдейтером.

**Comment by megoRU** [comment]
у старых тоже слетело

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/62006998-d6c14080-b150-11e9-98ec-3a1c28589574.png)
скачал а он битый. лол кек

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/62007018-1851eb80-b151-11e9-9e58-6c5bee40bcd1.png)
Все исправил. Можно закрывать
