### ISSUE TITLE
не сохраняються муты

### ISSUE THREAD

**Issue by rsgua** [SB-MaterialAdmin/Web#24]
после того как выдал мут он в сорес бане не появился я уже все перепробовал и не чего не помогает.
при чем это ток на накоторых серверах

**Comment by CrazyHackGUT** [comment]
Перезагрузите SourceComms. Он потерял соединение с БД.
Или возьмите SourceComms из оригинального SB++.

**Comment by CrazyHackGUT** [comment]
Давно обновлений не было. Закрываю.
