### ISSUE TITLE
Удаление использованых ваучеров 

### ISSUE THREAD

**Issue by valeologist** [SB-MaterialAdmin/Web#240]
Не удаляет ваучеры одной кнопкой 
![изображение](https://user-images.githubusercontent.com/44038528/62011798-d55e3b00-b185-11e9-86a0-5a3416cdf539.png)
![изображение](https://user-images.githubusercontent.com/44038528/62011803-ec049200-b185-11e9-95c6-28757980ed7c.png)
![изображение](https://user-images.githubusercontent.com/44038528/62011807-fde63500-b185-11e9-98fb-0d4356f6db7b.png)
![изображение](https://user-images.githubusercontent.com/44038528/62011810-0a6a8d80-b186-11e9-92f3-b4983086d648.png)
![изображение](https://user-images.githubusercontent.com/44038528/62011812-13f3f580-b186-11e9-8166-843aa2924866.png)

**Comment by CrazyHackGUT** [comment]
https://github.com/SB-MaterialAdmin/Web/commit/76adc92c88f206dfe9e45017369ced87280dceac

**Comment by CrazyHackGUT** [comment]
Исправлено.
