### ISSUE TITLE
Не могу войти на сайт

### ISSUE THREAD

**Issue by megoRU** [SB-MaterialAdmin/Web#242]
Ник и пароль меняю через MySQL
Пароль который для сброса  ну типа хеш (666e778948a27a70b426c685ae15d4b6d70539fc) 123456

![image](https://user-images.githubusercontent.com/23276305/62477274-55e9f080-b7b1-11e9-8e84-b3a796deabe7.png)

рофл в том что он не говорит что неверный пароль и логин. Но при этом не заходит...
Если левые данные ему скормить то он пишет неверный логин и пароль

**Comment by CrazyHackGUT** [comment]
Ссылку бы на сб.
Но судя по записи из консоли с ошибкой валидации токена, СБ не знает, на каком домене работает, потому как бы шлёт куку браузеру, но с пометкой для другого домена.

**Comment by megoRU** [comment]
а как сделать так чтобы он узнал на каком домене?

**Comment by megoRU** [comment]
кхм. само прошло как то... лел

**Comment by megoRU** [comment]
()()0 опять да фак

**Comment by CrazyHackGUT** [comment]
Он берёт информацию от сервера, из `$_SERVER` переменной.
Почему веб-сервер сам не знает, где он - отдельный вопрос.

Можно попробовать применить такой трюк. В самый вверх `/index.php` вписать (после `<?php`):
```php
$_SERVER['SERVER_NAME'] = "yourdomain.ru";
```

**Comment by megoRU** [comment]
не помогло(

**Comment by megoRU** [comment]
я понял.
