### ISSUE TITLE
_ в имени пользователя и имени базы данных

### ISSUE THREAD

**Issue by Hinja122** [SB-MaterialAdmin/Web#244]
Во время закачки сайта (/install/) там, где нужно указывать Имя Пользователя и Имя базы данных есть символ `_`, когда все успешно ввел, выдает такую ошибку (из-за этого символа "`_`")
https://imgur.com/jsmYang
https://i.imgur.com/abflAE0.png

**Comment by megoRU** [comment]
а загружать скрины сюда сложно???

**Comment by Hinja122** [comment]
![](https://i.imgur.com/jsmYang.png)

![](https://i.imgur.com/abflAE0.png)

**Comment by CrazyHackGUT** [comment]
Я пока не совсем понимаю, как именно здесь мешает символ нижнего подчёркивания, если MySQL сервер возвращаёт чёткую ошибку, что "кодировку UTF8" он "не знает" (возможно и такое, да).
Можно версию MySQL сервера?

**Comment by Hinja122** [comment]
Я чисто чтобы попробовать заказал минимальнейшую базу данных за 5 рублей, как раз таки там нету "_", и там сработало все без проблем

**Comment by CrazyHackGUT** [comment]
На том же хосте или другом? 
Если другой - 
```
сервер возвращает четкую ошибку, что "кодировку UTF8" он "не знает"
```
Потому на сервере с `_` и не работает.

**Comment by Hinja122** [comment]
на том же хостинге база данных с _
на другом хостинге, который удачно использовал без _

**Comment by Hinja122** [comment]
Прочитал FAQ, нашел там
A.: Обратите внимание, что MariaDB в данный момент не
    поддерживается!

**Comment by CrazyHackGUT** [comment]
Мария поддерживается, но частично.
Можете написать мне в Telegram, попробуем разобраться.
https://t.me/kruzya_stall

**Comment by CrazyHackGUT** [comment]
Проблему, вроде как, решили в ЛС.
