### ISSUE TITLE
Нельзя скачать демку

### ISSUE THREAD

**Issue by valeologist** [SB-MaterialAdmin/Web#245]
![изображение](https://user-images.githubusercontent.com/44038528/63647802-377f7100-c72f-11e9-9c0c-1d71aa3776d3.png)
![изображение](https://user-images.githubusercontent.com/44038528/63647803-3e0de880-c72f-11e9-8e15-547109e09b91.png)
![изображение](https://user-images.githubusercontent.com/44038528/63647806-482fe700-c72f-11e9-948e-f5d66c5685d7.png)
![изображение](https://user-images.githubusercontent.com/44038528/63647810-52ea7c00-c72f-11e9-8c75-315c2292b07e.png)
![изображение](https://user-images.githubusercontent.com/44038528/63647845-c8eee300-c72f-11e9-9985-ed507d38ee9f.png)

**Comment by CrazyHackGUT** [comment]
Как выяснилось в тот же день, попросту необновленный `getdemo.php`.
