### ISSUE TITLE
setProperty is not a function at ShowBox

### ISSUE THREAD

**Issue by kENNYx7** [SB-MaterialAdmin/Web#246]
После установки скрипта при авторизации ничего не происходит, просто бесконечная загрузка, а в консоли такая ошибка: Uncaught TypeError: $(...).setProperty is not a function
    at ShowBox (sourcebans.js:1043)
    at XMLHttpRequest.r.onreadystatechange (xajax.js:109)
Помогите решить сей трабл
![Снимок](https://user-images.githubusercontent.com/41576108/63705391-acd56980-c835-11e9-9dc9-5dec943ad5ad.PNG)

**Comment by CrazyHackGUT** [comment]
CTRL + F5, после чего должно заработать.
Если не помогло - сбросьте кеш у CloudFlare/на веб-сервере.

Видя скриншот, вижу, что ранее стоял какой-то иной сб. Потому вышеуказанные советы должны помочь.

**Comment by kENNYx7** [comment]
Действительно, очистка кэша помогла.
Теперь вижу такую ошибку вверху страницы:
Deprecated: Function create_function() is deprecated in /home/zpaxnjup/public_html/retake/bans/includes/smarty/Smarty_Compiler.class.php on line 269

**Comment by CrazyHackGUT** [comment]
Решается чтением форума.
Нужно либо версию PHP понизить до 7.0 (выше уже "не поддерживается"; часть функций будет удалена в будущем), либо в `init.php`, здесь:
https://github.com/SB-MaterialAdmin/Web/blob/release_1154/web_upload/init.php#L118-L119
Заменить `1` на `0`, и `E_ALL ^ E_NOTICE` - тоже на `0`.

**Comment by kENNYx7** [comment]
`Решается чтением форума.` - понимаю, раз вы мне помогли с первой проблемой, я решил воспользоваться и решить с вашей помощью вторую.
Спасибо, все пофиксил

**Comment by megoRU** [comment]
@CrazyHackGUT а какой пых ставить? до 7? это 5.6??

**Comment by West14** [comment]
> 
> 
> @CrazyHackGUT а какой пых ставить? до 7? это 5.6??

На 7.0 и 7.1 заводится без деприкейтов.

**Comment by megoRU** [comment]
@West14 у меня просто 7.3.8 вроде все ок

**Comment by CrazyHackGUT** [comment]
@megoRU, в девелоперке нужные изменения внесены уже по-умолчанию. В релизе - будет эррорить.
