### ISSUE TITLE
Уведомление не пропадает.

### ISSUE THREAD

**Issue by West14** [SB-MaterialAdmin/Web#251]
**Описание ошибки**
При выдаче мута\гага игроку, у которого уже имеется активный мут\гаг, появляется уведомление о наличии онного и его невозможно закрыть, само не пропадает.

**Шаги для воспроизведения**
Выдать мут\гаг игроку, у которого он уже имеется.

**Скриншоты**
![image](https://user-images.githubusercontent.com/30056636/64066879-08ce3280-cc28-11e9-88c9-1211e5a9a0d7.png)

Единственный вариант его закрыть - обновить страницу.
Я считаю, что должна присутствовать возможность закрыть это уведомление.

**Comment by CrazyHackGUT** [comment]
Вроде, исправил, но нужно проверить.

**Comment by West14** [comment]
Проверил, работает корректно.
