### ISSUE TITLE
Не показывает ник админка который забанил через сервер

### ISSUE THREAD

**Issue by Davidos15** [SB-MaterialAdmin/Web#254]
Когда чела банишь через сайт всё показывает, а когда через сервер, то пишет вместо ника админа который забанил, тип неизвестный админ. Это может и за того что я криво базу с админами перенёс, но иногда показывает некоторые баны, а может ещё что использую выдачу по группам серверов.
PHP 7.1
Apache 2.4.25
nginx 1.16.1
Версия плагина Ma: 0.7.8-070a8cb
Версия веба: 1.16, ластовый commit

**Comment by CrazyHackGUT** [comment]
Неплохо было бы взглянуть на базу. Напишите в [ВК](https://vk.com/spy__cat), приложив дамп.

**Comment by CatRuby** [comment]
решилась проблема? Замечал что-то подобное у себя

**Comment by CrazyHackGUT** [comment]
Опять же, нужны дампы. Хотя бы таблицу админов (`sb_admins`). И уточнить плагин, ибо два плагина слегка по разному ищат админов.

**Comment by Davidos-HDT** [comment]
@CrazyHackGUT Я тебе в вк писал, на счет того что сайт не видит админа, когда админка через группы сервера выдана, ты нашел фикс для этой проблемы, а то уже нужно?
