### ISSUE TITLE
Установка dev версии

### ISSUE THREAD

**Issue by Dancbeunny98** [SB-MaterialAdmin/Web#259]
Попытался установить версию с гита (не релиз) ничего не вышло. Все делал по инструкции. Что может быть не так? (500 ошибка весит)

**Comment by hirowatch** [comment]
удалить файл db.php и обновитсЯ еще раз не?

**Comment by CrazyHackGUT** [comment]
Что и как Вы делаете?

**Comment by Dancbeunny98** [comment]
> удалить файл db.php и обновитсЯ еще раз не?

Спасибо. Помог. Почему-то со второго раза только заработало. Странно.
