### ISSUE TITLE
Идеи, пожелания, недочёты и ошибки нового серверного плагина

### ISSUE THREAD

**Issue by RED4911** [SB-MaterialAdmin/Web#26]
Поставил на тест новый серверный плаг, к админке доступ пропал. Так же заметил что не создаются файлы с группами и админами в папке.

**Comment by CrazyHackGUT** [comment]
1). Логи ошибок и лог самого плагина (файл _materialadmin.log_ в _/addons/sourcemod/logs_) в студию.
2). А конфиги настроены?
3). А в **databases.cfg** ветку _sourcebans_ переименовал в _materialadmin_?

**Comment by RED4911** [comment]
в databases.cfg ветку sourcebans переименовал в materialadmin и все заработало. Вы где нибудь сделайте пометку об этом для других.

**Comment by Grey-rus** [comment]
описание есть тут http://hlmod.ru/threads/alpha-material-admin-refork-na-osnove-sb-1-5-4-7-bootstrap-3.36382/page-128#post-282196 и серверная часть в бете.

**Comment by RED4911** [comment]
Еще один баг! После смены карты админка слетает и пишет в консоли у ван нет доступа.

**Comment by Grey-rus** [comment]
Исправил, спасибо за информацию.

**Comment by RED4911** [comment]
Этот баг идет шел с 0.6b и почему то ни кто не сообщил до меня. Я думал что вы его пофиксили в 0.7 вот и не писал до сегодняшнего момента.

**Comment by Grey-rus** [comment]
Этот баг был с начальной версии, не сообщали наверно потому что ни кто не ставит((
Готовится ещё версия, я там ещё кое что изменил и исправил что удалось логически найти.

**Comment by RED4911** [comment]
Ну я поставил ))) Буду дальше смотреть.

**Comment by RED4911** [comment]
есть такая вкладка обновить список админов из за него слетают админки
насчет
мутов
муты работают при оффлайн бане
баны то работают то нет, короче непонятно у кого как.

**Comment by Grey-rus** [comment]
Пожалуйста предоставляйте лог плагина ещё.

**Comment by RED4911** [comment]
`L 12/03/2016 - 16:49:03: [SM] Exception reported: Client index 0 is invalid
L 12/03/2016 - 16:49:03: [SM] Blaming: materialadmin.smx
L 12/03/2016 - 16:49:03: [SM] Call stack trace:
L 12/03/2016 - 16:49:03: [SM]   [0] KickClient
L 12/03/2016 - 16:49:03: [SM]   [1] Line 672, materialadmin/function.sp::CreateSayBanned
L 12/03/2016 - 16:49:03: [SM]   [2] Line 516, materialadmin/database.sp::CreateDB
L 12/03/2016 - 16:49:03: [SM]   [3] Line 276, materialadmin/database.sp::SQL_Callback_CheckBanInBd
L 12/03/2016 - 23:21:49: [SM] Exception reported: Client index 0 is invalid
L 12/03/2016 - 23:21:49: [SM] Blaming: materialadmin.smx
L 12/03/2016 - 23:21:49: [SM] Call stack trace:
L 12/03/2016 - 23:21:49: [SM]   [0] KickClient
L 12/03/2016 - 23:21:49: [SM]   [1] Line 672, materialadmin/function.sp::CreateSayBanned
L 12/03/2016 - 23:21:49: [SM]   [2] Line 516, materialadmin/database.sp::CreateDB
L 12/03/2016 - 23:21:49: [SM]   [3] Line 276, materialadmin/database.sp::SQL_Callback_CheckBanInBd
`

**Comment by Grey-rus** [comment]
Можно уточни это при каком бане? как бан был проезведён когда эта ошибка произошла, если не знаете я вроде нашёл причину этой ошибки.

**Comment by RED4911** [comment]
Не знаю. Это со слов админов.

**Comment by Grey-rus** [comment]
Вроде исправил.

**Comment by Grey-rus** [comment]
у тебя какая игра?

**Comment by Grey-rus** [comment]
если не кс го то можешь попробовать новый способ показа сообщения забаненному
// 1. новый вариант 0. старый. на кс:го не поддерживается новый вариант
		"BanSayPanel"		"1"
это в конфиге поменять на 1.

**Comment by RED4911** [comment]
кс го у меня

**Comment by Grey-rus** [comment]
тогда не стоит, пиши ещё что заметишь, и чаще заглядывай на гитхаб за новой версией.

**Comment by RED4911** [comment]
Я и так тут часто. Все новшества сразу ставлю.

**Comment by RED4911** [comment]
Муты не снимаются. Нажимаешь в админке снять все муты и ничего как висели муты на сайте так и висят.

**Comment by Grey-rus** [comment]
Исправил, жди новой версии.

**Comment by RED4911** [comment]
L 12/04/2016 - 16:10:41: [SM] Exception reported: Language phrase "No reason" not found
L 12/04/2016 - 16:10:41: [SM] Blaming: materialadmin.smx
L 12/04/2016 - 16:10:41: [SM] Call stack trace:
L 12/04/2016 - 16:10:41: [SM]   [0] FormatEx
L 12/04/2016 - 16:10:41: [SM]   [1] Line 474, materialadmin/menu.sp::MenuHandler_MenuTypeMute

**Comment by RED4911** [comment]
И как я понял предопределения("Overrides") не работают, не вносятся в конфиг групп

**Comment by Grey-rus** [comment]
Обнови транслит, про "Overrides" поподробней?
Что и куда прописать, чтоб повторить у себя, я этим не знаком.

**Comment by Grey-rus** [comment]
нашёл ошибки в загрузке конфига админа, вроде исправил.

**Comment by RED4911** [comment]
Сейчас вообще почему то конфиги админов и групп перестали создаваться.

Вот пример предопределений в конфиге которые должны туда прописываться 

	"Admin2"
	{
		"flags"		"abcdfgjkn"
		"immunity"		"60"
		"Overrides"
		{
			"sm_freeze"		"deny"
			"sm_drug"		"deny"

**Comment by Grey-rus** [comment]
они теперь по другому пути создаются, configs/materialadmin/admin/
при обновление плагина проверяй структуру папок, может поменяться расположение файлов.

**Comment by RED4911** [comment]
Ни одной папки не создал он.

**Comment by Grey-rus** [comment]
Их надо самому создавать, плагины этого не умеют. Учись правильно обновлять плагины!

**Comment by CrazyHackGUT** [comment]
Почему не умеют? Функция для этого же есть. https://sm.alliedmods.net/new-api/files/CreateDirectory

**Comment by RED4911** [comment]
CrazyHackGUT правильно сказал. Даже старый плаг умеет,  а тут на тебе и не умеет

**Comment by RED4911** [comment]
Потестил. Конфиги создаются в папке admin, но сама папка не создается автоматически. Вот можешь посмотреть вроде тут все расписано по созданию папок http://world-source.ru/forum/100-2298-1

**Comment by Grey-rus** [comment]
Я её туда добавил, но гитхаб видать нах посла из за того что она пустая, сделал в плагине создание папки, обновись.

**Comment by RED4911** [comment]
Заметил еще баг что после разрыва соединения с базой плаг перестает работать пока полностью не перезагрузишь сервер.

**Comment by RED4911** [comment]
Так же если закинул этот плаг и сменить карту то же самое плаг не заработает до полного рестарта сервера

**Comment by Grey-rus** [comment]
Про последнее, он работает просто меню не добавилось, исправлено в последней версии, про перво проверю.

**Comment by RED4911** [comment]
Поставлю последнюю и тоже проверю снова

**Comment by Meowmurmur** [comment]
Можно сделать для префикса [MA] другой цвет, чтобы он выделялся? А то сейчас у него жёлтый цвет и он просто сливается с текстом. (v34)

**Comment by Grey-rus** [comment]
Правь исходники. В этой функции void PrintToChat2(int iClient, const char[] sMesag, any ...)

**Comment by Meowmurmur** [comment]
Знал бы я ещё что нужно там добавить, чтобы тег был зелёным :D

**Comment by RED4911** [comment]
Сделать отключение аутефикации по логину и паролю.

**Comment by CrazyHackGUT** [comment]
Это не относится к серверному плагину, и находится в TODO.

**Comment by Grey-rus** [comment]
Тег [MA] вынесу в транслит для чата чтоб можно было сделать цвета.

**Comment by Meowmurmur** [comment]
а как эти цвета то применить? Или это ещё не до конца реализовано?

**Comment by Grey-rus** [comment]
Цвета уже давно сделаны, в описание есть теги для цветов.

**Comment by Meowmurmur** [comment]
У меня походу с головой всё плохо, ибо я не могу понять что нужно делать -_-

**Comment by Grey-rus** [comment]
пример "#3[#4MA#3]#1"

**Comment by Meowmurmur** [comment]
На 34 походу не работает.
![de_chateau0000](https://cloud.githubusercontent.com/assets/13346898/21423894/1fc8739c-c848-11e6-8ead-e0fbcbed8102.jpg)

**Comment by Grey-rus** [comment]
цвет меняй в транслите, а не в исходнике.

**Comment by Meowmurmur** [comment]
Ну так я и добавляю в файл перевода. Или "транслит" это не файл перевода? -_-

**Comment by Grey-rus** [comment]
Нашёл причину, исправлю.

**Comment by Meowmurmur** [comment]
Теперь всё работает. Ещё вопрос, можно ли сделать, чтобы новый вариант сообщения забаненному показывался не только при самом бане, а и при попытке данного игрока зайти на сервер? Тк сейчас оно показывается только при бане, а при попытке зайти просто пишет, что стим айди забанен.

**Comment by Grey-rus** [comment]
При первом перезаходе показывает это, но банется на время указанное в конфиге, сделано против спама презаходов, тем самым облегчает бд.

**Comment by Meowmurmur** [comment]
Поставил плагин на 3 сервера (версия плагина самая последняя), после этого вроде всё норм было и я ушёл спать. Но попытавшись утром зайти в банлист словил вот такую хрень.
![screenshot_2016-12-23-08-56-25](https://cloud.githubusercontent.com/assets/13346898/21448872/fa13766c-c8ef-11e6-85eb-04f1af960131.png)
Отключил плагин на одном из серверов - всё нормализовалось. Если нужны какие-то логи, всё предоставлю)

**Comment by CrazyHackGUT** [comment]
Писали об этом неоднократно в конференции бета-тестеров в ВКонтакте. Вчера я предпринял попытку фикса, но она была неудачна. Сейчас ещё один вариант запилил, попробуй.

**Comment by RED4911** [comment]
`L 12/23/2016 - 22:21:22: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/23/2016 - 22:21:22: [SM] Blaming: materialadmin.smx
L 12/23/2016 - 22:21:22: [SM] Call stack trace:
L 12/23/2016 - 22:21:22: [SM]   [0] Database.Query
L 12/23/2016 - 22:21:22: [SM]   [1] Line 192, materialadmin/database.sp::BdGetMuteType
L 12/23/2016 - 22:21:22: [SM]   [2] Line 349, materialadmin/database.sp::DoCreateDB
L 12/23/2016 - 22:21:22: [SM]   [3] Line 239, materialadmin/function.sp::GetClientToBd
L 12/23/2016 - 22:21:22: [SM]   [4] Line 760, materialadmin/menu.sp::OnlineClientSet
L 12/23/2016 - 22:21:22: [SM]   [5] Line 713, materialadmin/menu.sp::MenuHandler_MenuMReason`

**Comment by RED4911** [comment]
L 12/23/2016 - 22:42:55: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/23/2016 - 22:42:55: [SM] Blaming: materialadmin.smx
L 12/23/2016 - 22:42:55: [SM] Call stack trace:
L 12/23/2016 - 22:42:55: [SM]   [0] Database.SetCharset
L 12/23/2016 - 22:42:55: [SM]   [1] Line 1208, materialadmin/database.sp::OverridesDone

**Comment by CrazyHackGUT** [comment]
Мой косяк. Исправлю как только будет доступ к компьютеру. Это завтра к обеду примерно получается.

**Comment by RED4911** [comment]
Ну админки все слетели ))

**Comment by rsgua** [comment]
не выдает админки http://in-g.su/materialadmin.log

**Comment by CrazyHackGUT** [comment]
Закоммитил только что обновление от @Grey-rus. Попробуйте.

**Comment by vBDSK** [comment]
L 12/26/2016 - 15:50:56: SourceMod error session started
L 12/26/2016 - 15:50:56: Info (map "surf_10x_reloaded") (file "errors_20161226.log")
L 12/26/2016 - 15:50:56: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:50:56: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:50:56: [SM] Call stack trace:
L 12/26/2016 - 15:50:56: [SM] [0] Database.SetCharset
L 12/26/2016 - 15:50:56: [SM] [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:50:56: [SM] [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:51:26: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:51:26: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:51:26: [SM] Call stack trace:
L 12/26/2016 - 15:51:26: [SM] [0] Database.SetCharset
L 12/26/2016 - 15:51:26: [SM] [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:51:26: [SM] [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:52:45: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:52:45: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:52:45: [SM] Call stack trace:
L 12/26/2016 - 15:52:45: [SM] [0] Database.SetCharset
L 12/26/2016 - 15:52:45: [SM] [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:52:45: [SM] [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:53:00: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:53:00: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:53:00: [SM] Call stack trace:
L 12/26/2016 - 15:53:00: [SM] [0] Database.SetCharset
L 12/26/2016 - 15:53:00: [SM] [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:53:00: [SM] [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:53:39: Error log file session closed.

12/26/2016 - 15:58:47: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 15:58:47: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 15:58:47: [SM] Call stack trace:
L 12/26/2016 - 15:58:47: [SM] [0] Database.SetCharset
L 12/26/2016 - 15:58:47: [SM] [1] Line 1159, materialadmin/database.sp::AdminHash
L 12/26/2016 - 15:58:47: [SM] [2] Line 402, materialadmin/commands.sp::CommandWRehashAdm
L 12/26/2016 - 15:58:47: rcon from "": command "ma_wb_rehashadm

Через web панель добавил серверные разрешения и доступ к серверу себе.
В админку на сервере зайти не могу

L 12/26/2016 - 16:08:03: [new_sb/materialadmin.smx] map start ConnectBd
L 12/26/2016 - 16:08:04: [new_sb/materialadmin.smx] map start ConnectBd: yes
L 12/26/2016 - 16:08:04: [SM] Exception reported: Invalid database Handle 0 (error: 4)
L 12/26/2016 - 16:08:04: [SM] Blaming: new_sb/materialadmin.smx
L 12/26/2016 - 16:08:04: [SM] Call stack trace:
L 12/26/2016 - 16:08:04: [SM] [0] Database.SetCharset
L 12/26/2016 - 16:08:04: [SM] [1] Line 1208, materialadmin/database.sp::OverridesDone

**Comment by RED4911** [comment]
А можно как то сделать чтоб определенной группе можно было убрать или изменить время бана. Просто хочется чтоб например некоторые группы банили максимум на неделю например.

**Comment by CrazyHackGUT** [comment]
@RED4911 нет, но идея годная. Может, добавим.

**Comment by RED4911** [comment]
Да я думаю добавить нужно, найдутся те которым это понадобится, в особенности тем у кого сервов много и групп.

**Comment by rsgua** [comment]
сделайте список замученых на сервере и размут замученых что на сервере

**Comment by RED4911** [comment]
Много серверов. Админы жалуются что на некоторых серверах слетает админка и сервер приходится перезагружать.

**Comment by RED4911** [comment]
`L 02/05/2017 - 15:13:10: SourceMod error session started
L 02/05/2017 - 15:13:10: Info (map "de_asiimov") (file "errors_20170205.log")
L 02/05/2017 - 15:13:10: [SM] Exception reported: Script execution timed out
L 02/05/2017 - 15:13:10: [SM] Blaming: materialadmin.smx
L 02/05/2017 - 15:13:10: [SM] Call stack trace:
L 02/05/2017 - 15:13:10: [SM]   [1] Line 13, materialadmin/database.sp::ConnectSourceBan
L 02/05/2017 - 15:13:10: [SM]   [2] Line 196, C:\SourceMod_18\materialadmin.sp::OnPluginStart
L 02/05/2017 - 15:13:10: [SM] Unable to load plugin "materialadmin.smx": Error detected in plugin startup (see error logs)
L 02/05/2017 - 15:13:33: Error log file session closed.`

**Comment by TR1D** [comment]
Два поля для отметки, csgo, 0.3.4 beta

![1](https://cloud.githubusercontent.com/assets/16725731/22886782/6b2abc9a-f210-11e6-86d1-4e747e70b072.jpg)

**Comment by Grey-rus** [comment]
Так и должно быть, первое показывает тип мута или есть ли мут.

**Comment by vBDSK** [comment]
L 02/13/2017 - 19:21:09: [SM] Exception reported: Script execution timed out
L 02/13/2017 - 19:21:09: [SM] Blaming: new_sb/materialadmin.smx
L 02/13/2017 - 19:21:09: [SM] Call stack trace:
L 02/13/2017 - 19:21:09: [SM] [1] Line 1474, materialadmin/database.sp::SQL_Callback_QueryBekap
L 02/13/2017 - 19:22:22: [SM] Exception reported: Script execution timed out
L 02/13/2017 - 19:22:22: [SM] Blaming: new_sb/materialadmin.smx
L 02/13/2017 - 19:22:22: [SM] Call stack trace:
L 02/13/2017 - 19:22:22: [SM] [1] Line 1474, materialadmin/database.sp::SQL_Callback_QueryBekap

**Comment by CrazyHackGUT** [comment]
Все обсуждения нового плагина переносятся [сюда](https://github.com/SB-MaterialAdmin/NewServer), в связи с чем обсуждение закрывается.
