### ISSUE TITLE
Причины банов и мутов

### ISSUE THREAD

**Issue by e-zhuravlev** [SB-MaterialAdmin/Web#260]
Выпилить статические причины с шаблона.
Оставить только с БД чтоб было больше динамики

**Comment by CrazyHackGUT** [comment]
Взято в работу. В течении этих выходных попробую сделать.

**Comment by CrazyHackGUT** [comment]
Спасибо РКН за просранные сроки.

**Comment by MAGNAT2645** [comment]
Может лучше отделить причины бана и причины блокировки коммуникаций?
Просто при выдаче мута/гага не хочется видеть причину "Читы" в списке.

**Comment by megoRU** [comment]
Вообще в пункте управление банами нет мутов
только по такой ссылке можно
index.php?p=admin&c=comms

**Comment by MAGNAT2645** [comment]
![изображение](https://user-images.githubusercontent.com/11666918/71544183-badef680-299d-11ea-9d72-dcf8c0d3afbb.png)

**Comment by megoRU** [comment]
Ааа, но я имел ввиду тут)
![image](https://user-images.githubusercontent.com/23276305/71544205-22407a80-298d-11ea-9b40-29c2a2049d13.png)

**Comment by MAGNAT2645** [comment]
А, мне кажется, что пользоваться такой панелью не всегда удобно. Проще через ту кнопочку сразу перейти к нужной страничке.

**Comment by MAGNAT2645** [comment]
А вообще да, желательно бы добавить "Управление блокировками" (хз как лучше назвать) для коммуникации.

**Comment by megoRU** [comment]
Управление банами/мутам)
