### ISSUE TITLE
AJAX Call Failed на странице списка администраторов.

### ISSUE THREAD

**Issue by Davidos15** [SB-MaterialAdmin/Web#263]
Иногда выскакивает ошибка. Версия WEB 1.1.6 (526), PHP 7.1.
![image](https://user-images.githubusercontent.com/38360572/67562078-b80a2000-f726-11e9-8bb5-95a2eba35606.png)

**Comment by CrazyHackGUT** [comment]
> Too many connections

Слишком много одновременных подключений к базе. Поднимите лимит.
