### ISSUE TITLE
В блоке "Блокировки коммуникаций" неправильно отображаются Mute+Gag

### ISSUE THREAD

**Issue by sydro263** [SB-MaterialAdmin/Web#267]
1. Выдадим любому человеку мут или же гаг(будет лучше)
2. После выдачи перейдем на главную страницу
3. Видим блок Блокировки коммуникаций, там отображаются Никнеймы заблокированных игроков, а так же срок
4. Иконки у мутов отдельно, или же гагов отдельно, работают соответственно как и нужно. А вот же Мут+Гаг отображается в этом блоке как блокировка микрофона.
Итог: Неправильное отображение иконки у блокировки Мут+Гаг в блоке

**Comment by CrazyHackGUT** [comment]
На какой версии проверялось? Я в 1.1.6 кажется правил это, но не уверен.

**Comment by sydro263** [comment]
@CrazyHackGUT Версия 1.1.6 (526)

**Comment by CrazyHackGUT** [comment]
Только что проверил
![изображение](https://user-images.githubusercontent.com/12576822/68082562-d8795f00-fe37-11e9-9f42-4ad725d21313.png)

**Comment by sydro263** [comment]
А на главной странице как у вас отобразиться?(именно про неё я и говорил)

**Comment by sydro263** [comment]
В отдельной странице мутов
![изображение](https://user-images.githubusercontent.com/52104782/68082615-6c4b2b00-fe38-11e9-8c92-66c590d23bb4.png)
А вот и на главной 
![изображение](https://user-images.githubusercontent.com/52104782/68082621-7bca7400-fe38-11e9-8966-33b7110a591b.png)

**Comment by CrazyHackGUT** [comment]
А вот на главной не смотрел. Сейчас посмотрю, но скорее всего подтвердится.

**Comment by sydro263** [comment]
Хорошо, если что, напишите.

**Comment by CrazyHackGUT** [comment]
Проверьте теперь.

**Comment by sydro263** [comment]
@CrazyHackGUT ?

**Comment by kilroy98** [comment]
@sydro263 https://github.com/SB-MaterialAdmin/Web/commit/8ca166a2f74d7d1211f22459092c3b64f60418fa

**Comment by sydro263** [comment]
@kilroy98  Мой ответ почему-то переехал в самый вверх...
![изображение](https://user-images.githubusercontent.com/52104782/68085377-d0321b80-fe59-11e9-9151-d9de1d99d807.png)

**Comment by sydro263** [comment]
Это уже после фикса.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/68085415-eb992880-fe51-11e9-84a5-a417bb6c8a16.png)

после фикса

у вас помойму где то что то потеряно

**Comment by sydro263** [comment]
@megoRU в блоке на главной странице, ни в отдельной..

**Comment by megoRU** [comment]
на главной у меня нет такого блока

**Comment by sydro263** [comment]
![изображение](https://user-images.githubusercontent.com/52104782/68085602-0ec8d580-fe5c-11e9-8a56-e5fefbfddc15.png)
@megoRU Кхм? У меня есть.

**Comment by megoRU** [comment]
Версия 1.1.6 (526) А у тебя?

**Comment by sydro263** [comment]
Версия 1.1.6 (526)

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/68085684-a0344980-fe54-11e9-8625-243e8d03c4ee.png)
понял принял обработал

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/68085690-b3dfb000-fe54-11e9-9b43-e599d6709f05.png)
воспроизвелось

**Comment by sydro263** [comment]
Fixed.
