### ISSUE TITLE
В списке мутов/гагов не отображается подробная информация об админе

### ISSUE THREAD

**Issue by domikuss** [SB-MaterialAdmin/Web#272]
1. Перейдем в Список мутов/гагов
2. Кликнем по любой выданной блокировке
3. Видим, что подробной информации об админе нет, только возможно оставить комментарий.
P.S: Возможно это не баг, а фича. Да и в списке банов же подробная информация есть
![изображение](https://user-images.githubusercontent.com/52104782/70385874-0f004780-19ab-11ea-8151-516ef0f59d7a.png)

**Comment by megoRU** [comment]
воспроизвелось

**Comment by CrazyHackGUT** [comment]
Там админ и не был сделан.

**Comment by CrazyHackGUT** [comment]
Возможности проверить нет. Должно работать.

**Comment by sydro263** [comment]
Чуть позже отпишусь, как проверю.

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/70425640-a08eb880-1a82-11ea-86c8-47225e173a31.png)


@CrazyHackGUT что ты наделал)

**Comment by CrazyHackGUT** [comment]
*мат*

**Comment by sydro263** [comment]
@CrazyHackGUT Точно такая же ситуация, как и у человека выше =(

**Comment by CrazyHackGUT** [comment]
Я через 20 минут залью фикс.

**Comment by sydro263** [comment]
@CrazyHackGUT Ждём-с

**Comment by megoRU** [comment]
Крузя и сроки :)

**Comment by sydro263** [comment]
🔑

**Comment by Davidos-HDT** [comment]
@CrazyHackGUT 
An exception occured: [InvalidArgumentException] Invalid SteamID passed. in 
 1. /includes/classes/CSteamId.php on line 15
CSteamId::factory(string) in /pages/page.commslist.php at line 461
 2. include(string) in /includes/page-builder.php at line 147
 3. include_once(string) in /index.php at line 57

**Comment by megoRU** [comment]
не пофикшено
@CrazyHackGUT

**Comment by CrazyHackGUT** [comment]
Пора видимо разворачивать снова какую-нибудь эталонную демку, если на которой что-то не работает - нужно создавать Issue.
Попробуйте теперь.

**Comment by sydro263** [comment]
@CrazyHackGUT Уже начало показывать всё, но теперь нет инфы об STEAMID, VK и т.д
![изображение](https://user-images.githubusercontent.com/52104782/71065421-a1ae9c80-218a-11ea-96da-75b457168fca.png)

**Comment by CrazyHackGUT** [comment]
А при поиске? Там два разных запроса почему-то в мутлисте висит.

**Comment by sydro263** [comment]
@CrazyHackGUT При поиске точно так же
![изображение](https://user-images.githubusercontent.com/52104782/71065892-9740d280-218b-11ea-95de-a5c59894ab33.png)

**Comment by CrazyHackGUT** [comment]
Там есть два вида поиска. Один обычный по строке (и в причине ищет, и в никнейме, и в стиме), другой - расширенный (выбирается тип данных и они вводятся). Попробуйте оба.

**Comment by sydro263** [comment]
@CrazyHackGUT Проверил в обоих, всё точно так же, как и на скриншоте от меня выше

**Comment by sydro263** [comment]
@CrazyHackGUT  продолжаем ждать...

**Comment by megoRU** [comment]
Он уже исправил)

**Comment by megoRU** [comment]
https://github.com/SB-MaterialAdmin/Web/commit/54064011b3f9963576ce43b6f9287b1d4285dcd6

**Comment by megoRU** [comment]
@CrazyHackGUT 
![image](https://user-images.githubusercontent.com/23276305/71310965-93cb7680-242b-11ea-92d3-adf79a444b71.png)

Иногда долго грузиться страница. Кстати еще не получает steam id админа

**Comment by sydro263** [comment]
@megoRU Ну как бы я про это и говорил, что информации нет.

**Comment by sydro263** [comment]
@CrazyHackGUT ?

**Comment by CrazyHackGUT** [comment]
Сегодня установлю локально и посмотрю. Извиняйте, был занят, доступа к ПК не было.

**Comment by sydro263** [comment]
@CrazyHackGUT Спасибо, ждём.

**Comment by CrazyHackGUT** [comment]
Смотрю у себя локально. Только Стим не отображается.
![изображение](https://user-images.githubusercontent.com/12576822/71713728-5fd95380-2e24-11ea-8a5d-a31dc38469e3.png)

**Comment by sydro263** [comment]
@CrazyHackGUT странно, но сравнивная страницу с банами, и с мутами. можно увидеть такую картину.
Бан: 
![image](https://user-images.githubusercontent.com/52104782/71713841-cbbbbc00-2e24-11ea-8460-5cb18b90b351.png)
Мут:
![image](https://user-images.githubusercontent.com/52104782/71713846-d5ddba80-2e24-11ea-924c-e6611f908657.png)
Только имя админа

**Comment by CrazyHackGUT** [comment]
А опкеша случайно нет? Попробуйте его сбросить.

**Comment by sydro263** [comment]
@CrazyHackGUT ткните пальцем, не шарю 😭

**Comment by CrazyHackGUT** [comment]
https://github.com/amnuts/opcache-gui/raw/master/index.php
Эту штуку куда-нибудь на сервер закиньте, откройте в браузере и нажмите `Reset Cache`.

**Comment by sydro263** [comment]
@CrazyHackGUT сделал, посмотрел SB, ничего не изменилось

**Comment by sydro263** [comment]
@CrazyHackGUT так, я перезалил снова файлы, которые вы изменяли. Данные приходят все, кроме стима 
![image](https://user-images.githubusercontent.com/52104782/71714744-784b6d00-2e28-11ea-8403-6099adef3825.png)
(сорь за тупость)

**Comment by megoRU** [comment]
а мне не помогло....

**Comment by sydro263** [comment]
@CrazyHackGUT Ожидается?

**Comment by CrazyHackGUT** [comment]
Да, пока времени просто нет. Сегодня может поймаю момент.

**Comment by sydro263** [comment]
Ждём. :)

**Comment by domikuss** [comment]
@CrazyHackGUT  Видимо продолжаем ждать.

**Comment by domikuss** [comment]
🤔

**Comment by megoRU** [comment]
он вроде отошел от дел пока что
source: его телега

**Comment by megoRU** [comment]
@CrazyHackGUT @domikuss 

Крузя у тебя там не было выборки из SQL для **AD.authid admin_authid** и еще наверное кое что другое, но я так быстро фикс сделал.

Приложил архив с фиксом.

<details>
  <summary>Картинка</summary>

![image](https://user-images.githubusercontent.com/23276305/87228140-d47ae500-c3a7-11ea-9df7-f1fe09fc6473.png)
</details>

[page.commslist.zip](https://github.com/SB-MaterialAdmin/Web/files/4907056/page.commslist.zip)

P. S. Вот умора джавист исправил баг в PHP....

**Comment by domikuss** [comment]
> @CrazyHackGUT @domikuss 
> 
> Крузя у тебя там не было выборки из SQL для **AD.authid admin_authid** и еще наверное кое что другое, но я так быстро фикс сделал.
> 
> Приложил архив с фиксом.
> 
> <details>
>   <summary>Картинка</summary>
> 
> ![image](https://user-images.githubusercontent.com/23276305/87228140-d47ae500-c3a7-11ea-9df7-f1fe09fc6473.png)
> </details>
> 
> [page.commslist.zip](https://github.com/SB-MaterialAdmin/Web/files/4907056/page.commslist.zip)
> 
> P. S. Вот умора джавист исправил баг в PHP....
> 

Залью, отпишу. Заранее тоже спасибо

**Comment by domikuss** [comment]
@megoRU Всё работает. За фикс спасибо большое 👍 
P.S: "Будет снят" пропала информация, но это уже ладно, не самое критичное.

**Comment by megoRU** [comment]
Через 30 мин поправлю если найду. Я вроде понял где убрал

**Comment by megoRU** [comment]
@domikuss Вот пофиксил. Есть еще какие-то пожелания?

[page.commslist.zip](https://github.com/SB-MaterialAdmin/Web/files/4907334/page.commslist.zip)

**Comment by domikuss** [comment]
> @domikuss Вот пофиксил. Есть еще какие-то пожелания?
> 
> [page.commslist.zip](https://github.com/SB-MaterialAdmin/Web/files/4907334/page.commslist.zip)

@megoRU Всё прекрасно работает. Ещё раз большая благодарность вам. 😃 
Попросить бы Крузю залить это в сам репозиторий

**Comment by CrazyHackGUT** [comment]
Я залью, но позже. Времени пока вообще ни на что нет, работой поглощён.

**Comment by CrazyHackGUT** [comment]
Загрузил, спасибо @megoRU за потраченное время. Возможно позже я вернусь к активной разработке, но пока вот так.

**Comment by bigbrain911** [comment]
В результате пропали иконки перед никами, показывающие бан чата или войс.

Было и должно быть так:
![муты](https://user-images.githubusercontent.com/24904325/89293988-7d46f800-d667-11ea-853c-738b0ed138eb.PNG)

А получилось так:

![муты 2](https://user-images.githubusercontent.com/24904325/89294028-8c2daa80-d667-11ea-9967-73206fc074e6.PNG)

**Comment by megoRU** [comment]
Принято. Ща посмотрим. Где я накосячил

**Comment by megoRU** [comment]
Нашел вроде ошибка. Буду править

**Comment by megoRU** [comment]
Исправил. Ща сделаю для @CrazyHackGUT ветку
[page.commslist.zip](https://github.com/SB-MaterialAdmin/Web/files/5022149/page.commslist.zip)

**Comment by megoRU** [comment]
Готово
https://github.com/SB-MaterialAdmin/Web/pull/298
