### ISSUE TITLE
Добавить пункты в "Панель управления"

### ISSUE THREAD

**Issue by Davidos-HDT** [SB-MaterialAdmin/Web#274]
Нужно добавить пункты "Управление мутими/гагами" и "Управление меню" в "Панель управления" в мини панели они есть, а полной версии их нету.
![image](https://user-images.githubusercontent.com/38360572/71092628-4beceb00-21b0-11ea-8d70-983ee22ff421.png)
![image](https://user-images.githubusercontent.com/38360572/71092598-3d063880-21b0-11ea-99bb-5b523a94fbd7.png)

**Comment by BlackYuzia** [comment]
@CrazyHackGUT а есть смысл?
так то можно... но зочем? :eyes:

**Comment by BlackYuzia** [comment]
![image](https://user-images.githubusercontent.com/25010528/71874095-af23ca80-3129-11ea-8242-23c82b7c7b41.png)
@CrazyHackGUT осуждаю.
