### ISSUE TITLE
Не обновляется информация о сервере

### ISSUE THREAD

**Issue by GameFenix** [SB-MaterialAdmin/Web#287]
Не обновляется информация о сервере при обновлении страницы,или же при переходе на сервер и нажатия на "Обновить статус"
Версия 1.1.6 (526)
Скриншот с хоста:https://imgur.com/a/qNJvlSq
Скриншот с сайта:https://imgur.com/a/skRxsYb

**Comment by CrazyHackGUT** [comment]
Кеширование информации о сервере выключено хоть? Если включено, оно на сервер не пойдёт, если время жизни кеша не истекло.

**Comment by GameFenix** [comment]
Спасибо,проблема решена (выключил кеширование)
