### ISSUE TITLE
Ошибка после обновления PHP|MySQL (Ubuntu Server 18.04 => 20.04)

### ISSUE THREAD

**Issue by nikitoSha** [SB-MaterialAdmin/Web#291]
**Describe the bug**
После обновления операционки (с автоматическим обновлением php7.1 и mysql (старую версию не помню, но всё самое свежее было), появились ошибки в разных местах веб-приложения. Варианты ошибок:

1.

> AJAX Call Failed!
> 
> Error: the XML response that was returned from the server is invalid. Received:
> Fatal error: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli' at line 1] in EXECUTE("INSERT INTO sb_log(type,title,message, function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'function, query, aid, host, created)\n VALUES (\'m\',\'Бан добавлен\'\' at line 1] in EXECUTE(\"INSERT INTO sb_log(type,title,message, function, query, aid, host, created)\n VALUES (\'m\',\'Бан добавлен\',\'Бан против (STEAM_0:0:516249080) был добавлен, причина: [LuaZX] was banned at 30min. for using an AimBot (Automatic Route Guidance), срок: 45\',\'3: /includes/xajax.inc.php::AddBan(\\\'O.S.|Нервный\\\', \\\'0\ in /var/www/games/lunev_css_v34/server/cstrike/sourcebans/includes/adodb/adodb-errorhandler.inc.php on line 79
> You have whitespace in your response.

2.

> Fatal error: mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli' at line 1] in EXECUTE("INSERT INTO sb_log(type,title,message, function, query, aid, host, created) VALUES ('e','PHP Error','[256] mysqli error: [1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'function, query, aid, host, created)\n VALUES (\'m\',\'Игрок разбан�\' at line 1] in EXECUTE(\"INSERT INTO sb_log(type,title,message, function, query, aid, host, created)\n VALUES (\'m\',\'Игрок разбанен\',\'\\\'O.S.|Нервный\\\' (STEAM_0:0:516249080) был разбанен\',\'2: /includes/page-builder.php::include(\\\'/var/www/games/lunev_css_v34/server/cstrike/sourcebans/pages/page.banlist.php\\\') - 139
> \\n1: /index.php::incl in /var/www/games/lunev_css_v34/server/cstrike/sourcebans/includes/adodb/adodb-errorhandler.inc.php on line 79

Проанализировал ошибку, посмотрел, где и что. В общем, проблема связана с логированием действий в приложении. Файл **CSystemLog.php** строки: 91 и 105 (выполнение запросов к СУБД.

Временное решение проблемы - отключение логирования (закомментировать данные строки).

Хотелось бы увидеть рабочий вариант. Может, появилась проблема с экранированием строк? Пока не могу тщательней протестировать.

**Comment by CrazyHackGUT** [comment]
Только сейчас зашел на Гит и увидел. Сегодня попробую поправить.
