### ISSUE TITLE
[Error] Call to a member function MoveNext() on bool 

### ISSUE THREAD

**Issue by GARAYEV-PG** [SB-MaterialAdmin/Web#302]
An exception occured: [Error] Call to a member function MoveNext() on bool in /includes/system-functions.php on line 1183
GetUserAvatar(NULL) in /pages/header.php at line 122
include(string) in /includes/system-functions.php at line 90
BuildPageHeader() in /includes/page-builder.php at line 137
include_once(string) in /index.php at line 57

Used /updater and got result: Обновление... Проверка текущей версии SourceBans... 603 Обновления не нужны. Удалите папку updater!

so using updater din't help.

When i tried on xamp localhost, everything worked fine. Php version is supported.

I was using sourcebans++ 1.6.3 version and everything was great, wanted to use this version.

Any help?

**Comment by CrazyHackGUT** [comment]
Show `version` value from `sb_settings`.

**Comment by GARAYEV-PG** [comment]
i already fixed it, you can close this issue
