### ISSUE TITLE
[Баг] Ваучеры не работают

### ISSUE THREAD

**Issue by MAGNAT2645** [SB-MaterialAdmin/Web#303]
SB в логах пишет:
![изображение](https://user-images.githubusercontent.com/11666918/93686485-0ad38f80-fad0-11ea-9ae0-1ce337e4d85f.png)

Но на самом деле администратор не появляется в БД (ну и в списке администраторов конечно же).
При попытке войти под нового (созданного через ваучер) админа пишет `Неверный логин и/или пароль`.

А ещё в логах (а также на странице банов) отображается какой-то "левый" IP (и он вроде как каждый раз случайный), хотя я не использую какие-либо VPN или прокси.

**Comment by megoRU** [comment]
Слабо верится. 
Пойду попробую сделать

**Comment by megoRU** [comment]
![image](https://user-images.githubusercontent.com/23276305/93688975-e0370600-fad2-11ea-85d0-81700c90168d.png)

Ну вообщем я зря потратил время. 

P. S. Кузя лучше бы мои Pull requests залил в основную ветку)

**Comment by MAGNAT2645** [comment]
> 
> 
> Слабо верится.
> Пойду попробую сделать

И как же мне доказать? (во-первых, я использую последнюю Dev-версию с ветки `master` (от 22 июля)
P.S. Лучше бы помог...

**Comment by megoRU** [comment]
Переустановить SB
Скинуть мне файлы PHP которые связаны с страницей где идёт отправка данных в БД при активации ваучера. 
Конкретный файл php скажу как буду да пк

**Comment by MAGNAT2645** [comment]
Переустанавливал (правда давно, а переустанавливать полностью не хочется т.к. в основном всё работает стабильно, просто есть некоторые раздражающие баги) + не так давно обновлялся (через `/update`) до последнего коммита с основной (master) ветки.

**Comment by megoRU** [comment]
`page.vay4er.php`
вот это отвечает за отправку данных

**Comment by MAGNAT2645** [comment]
```<?php
if(!defined("IN_SB")){echo "Ошибка доступа!";die();}
global $theme, $userbank;
	if($GLOBALS['config']['page.vay4er']!="1"){
		CreateRedBox("Ошибка", "Страница отключена.");
		PageDie();
	}
if(isset($_POST['pay_v4']) && !empty($_POST['pay_v4']))
{
	preg_match("@^(?:http://)?([^/]+)@i", $_SERVER['HTTP_HOST'], $match);	
	if($match[0] != $_SERVER['HTTP_HOST']) 
	{ 
		echo '<div class="alert alert-danger" role="alert" id="msg-red"><h4>Ошибка!</h4><span class="p-l-10">Произошла неизвестная ошибка.</span></div>';
	
		require(TEMPLATES_PATH . "/footer.php");
		$log = new CSystemLog("w", "Попытка взлома", "Попытка активации ваучера с использованием: " . $_SERVER['HTTP_HOST']);
		exit();
	}
	
	$validation = $_POST['pay_v4'];
	if(strlen($validation) < 19)
	{
		echo '<div class="alert alert-danger" role="alert" id="msg-red"><h4>Ошибка!</h4><span class="p-l-10">Ваучер слишком короткий.</span></div>';
		require(TEMPLATES_PATH . "/footer.php");
		exit();
	}
	
	$validation = str_replace("-", "", $validation);
	$validation = RemoveCode($validation);
	$validation = preg_replace("/[^0-9]/", '', $validation);
	$qwr = $GLOBALS['db']->GetOne("SELECT `activ` FROM `" . DB_PREFIX . "_vay4er` WHERE `value` = '".$validation."'");
	if($qwr != "0" && $qwr == "1"){
		$vaxye_vso = "1";
		//echo "VSO OK";
		$user_group_web = $GLOBALS['db']->GetOne("SELECT `group_web` FROM `" . DB_PREFIX . "_vay4er` WHERE `value` = '".$validation."'");
		if($user_group_web == "" || $user_group_web == "0"){
			$user_group_web = "Не указана/Нет группы";
		}
		$user_group_srv = $GLOBALS['db']->GetOne("SELECT `group_srv` FROM `" . DB_PREFIX . "_vay4er` WHERE `value` = '".$validation."'");
		if($user_group_srv == "" || $user_group_srv == "0"){
			$user_group_srv = "Не указана/Нет группы";
		}
		$pay_days = $GLOBALS['db']->GetOne("SELECT `days` FROM `" . DB_PREFIX . "_vay4er` WHERE `value` = '".$validation."'");
		if($pay_days == "0"){
			$pay_days_t = "Навсегда";
		}else{
			$pay_days_t = $pay_days." Дней";
		}
		$theme->assign('days', $pay_days_t);
		$theme->assign('gr_web', $user_group_web);
		$theme->assign('gr_srv', $user_group_srv);
		$theme->assign('klu4ik', $validation);
		
		$servers_num = $GLOBALS['db']->GetOne("SELECT `servers` FROM `" . DB_PREFIX . "_vay4er` WHERE `value` = '".$validation."'");
		$add_srv = "";
		$add_srv_sql = "''";
		
		if($servers_num == ""){
			$add_srv = "
			var el = document.getElementsByName('servers[]');
			var svr = '';
			for(i=0;i<el.length;i++){
				if(el[i].checked){
					svr = svr + ',' + el[i].value;
				}
			}";
			$add_srv_sql = "svr";
		}
		
		echo "<script>		
		function AddAdmin_pay(){	
			".$add_srv."
			xajax_AddAdmin_pay('','', document.getElementById('user_login').value, //Admin name
							document.getElementById('user_steamid').value, //Admin Steam
							document.getElementById('user_email').value, // Email
							document.getElementById('password').value,//passwrds
							document.getElementById('password2').value,
							'', //servergroup
							'', 
							'-1',
							0,
							0,
							'',
							".$add_srv_sql.",
							document.getElementById('skype').value,
							'',
							document.getElementById('vk').value,
							'".$validation."');}</script>";
		$theme->assign('servers', $servers_num);
	}else{
		$vaxye_vso = "0";
		//echo "VSO NE OK 1";
	}
}
else
{
	$vaxye_vso = "0";
	//echo "VSO NE OK 2";
}


$servers = $GLOBALS['db']->GetAll("SELECT * FROM `" . DB_PREFIX . "_servers`");
$server_list = array();
$serverscript = "<script type=\"text/javascript\">";
foreach($servers AS $server)
{
    $serverscript .= "xajax_ServerHostPlayers('".$server['sid']."', 'id', 'sa".$server['sid']."');";
	$info['sid'] = $server['sid'];
	$info['ip'] = $server['ip'];
	$info['port'] = $server['port'];
	array_push($server_list, $info);
}


$serverscript .= "</script>";

$theme->assign('server_list', $server_list);
$theme->assign('server_script', $serverscript);


$theme->assign('param', $vaxye_vso);
$theme->display('page_vay4er.tpl');
?>
```

**Comment by megoRU** [comment]
Лучше бы файлом.
Вроде все ок.

Какой php на сервере.
Браузер хром?

**Comment by MAGNAT2645** [comment]
Да, про файл не подумал...

PHP:
```
PHP 7.0.33-0ubuntu0.16.04.15 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.15, Copyright (c) 1999-2017, by Zend Technologies
```

Использую Firefox, но тут браузер вряд ли виноват т.к. я выдавал код ваучера другому пользователю - у него тоже самое.

**Comment by megoRU** [comment]
тогда я грешу на mysql.
Она локально на сервере или где-то в другом месте?

**Comment by MAGNAT2645** [comment]
SB и MySQL на одном сервере

**Comment by MAGNAT2645** [comment]
Странно что добавление админов вручную работает нормально (всё вносится в БД)

**Comment by megoRU** [comment]
Да скорее всего это и проблема. Кто-то писал что у него онлайн кэшируется

**Comment by megoRU** [comment]
на клауде сделай страницы uncached page

**Comment by MAGNAT2645** [comment]
> 
> 
> Да скорее всего это и проблема. Кто-то писал что у него онлайн кэшируется

Я писал про страницу серверов. Там кэшируется список игроков.

**Comment by MAGNAT2645** [comment]
> 
> 
> на клауде сделай страницы uncached page

Не знаю где это. Вижу только `Cache Level` в `Page Rules`.

**Comment by megoRU** [comment]
```Page Rules```
вроде там. я особо не юзаю cloud не вижу смысла когда защита 2TB

**Comment by MAGNAT2645** [comment]
Вроде установил `Cache Level` на `Bypass` для `/sourcebans/*`, потом сделал очистку кэша (`Cache Purge`).
После этого страница грузилась чуть дольше (видимо пересборка кэша), попробовал ещё раз зарегистрироваться через Ваучер.
Пишет:
![изображение](https://user-images.githubusercontent.com/11666918/93710133-a9f29880-fb5d-11ea-865a-012762a1f1f6.png)

В системном логе:
`Ваучер 7504224761681401 был успешно активирован! Администратор (TEST) был успешно добавлен!`

При попытке войти:
![изображение](https://user-images.githubusercontent.com/11666918/93710145-baa30e80-fb5d-11ea-840b-ae94fa0991cc.png)

Сам ваучер закрылся.
![изображение](https://user-images.githubusercontent.com/11666918/93710174-fd64e680-fb5d-11ea-8b4b-06eaa90522ed.png)

**Comment by megoRU** [comment]
мб тебе юзать не cloud а ddos guard там тоже бесплатно можно намутить

**Comment by megoRU** [comment]
https://ddos-guard.net/ru/store/web

**Comment by MAGNAT2645** [comment]
Я сначала хочу убедиться, что это из-за CloudFlare (а вдруг это не так?).

**Comment by MAGNAT2645** [comment]
Перешёл в Dev Mode и сделал `Purge Everything` (сброс кэша со всех страниц), щас попробую ещё раз создать ваучер и зарегистрироваться.

**Comment by MAGNAT2645** [comment]
> 
> 
> мб тебе юзать не cloud а ddos guard там тоже бесплатно можно намутить

Я CloudFlare ещё для SSL использую (в `Page Rules` выставил редирект с `http` на `https`).

**Comment by megoRU** [comment]
у тебя сайт на vds?

**Comment by MAGNAT2645** [comment]
В общем, я не думаю, что тут CloudFlare виноват т.к. даже при Dev Mode и сбросе кэша происходит этот баг.
![изображение](https://user-images.githubusercontent.com/11666918/93710435-2e461b00-fb60-11ea-8302-7da52578ac24.png)

**Comment by megoRU** [comment]
У меня вот связка debian + plesk и все. Ключи активации можно беслпатно получать)

**Comment by megoRU** [comment]
+еще кеширует +- нормально.

Но ярые линуксойды кинут в меня помидоры за использование Plesk)

**Comment by MAGNAT2645** [comment]
SB делает вид, что ваучер активирован и все введённые данные записываются в лог и в функцию xajax, но на деле эти данные не записываются в БД (потому и не получается залогиниться).

**Comment by megoRU** [comment]
но сразу скажу Plesk и cloudflare не дружит.
там просто криворукие сидят на зарплате

**Comment by megoRU** [comment]
Это мб из-за того что клауд думает это статическая страница и её не обрабатывает.
Кстати отключи мб cжатие на клауде js css

**Comment by MAGNAT2645** [comment]
Сейчас бы понять как это сделать (да и можно ли вообще) :)

**Comment by MAGNAT2645** [comment]
> 
> 
> Это мб из-за того что клауд думает это статическая страница и её не обрабатывает.
> Кстати отключи мб cжатие на клауде js css

Я во всех этих веб-штуках только самую-самую основу понимаю (не специалист короче). У меня прописано сжатие файлов в htaccess как я помню.

**Comment by megoRU** [comment]
htaccess вроде только доступ и лимит контролирует.
У тебя еще апатч чтоле?

**Comment by MAGNAT2645** [comment]
Да, думал на nginx перейти, но не знаю как (да и возможно есть риск потерять какие-то данные или существующую конфигурацию)

**Comment by megoRU** [comment]
на vds у тебя только mysql и сайты?

**Comment by MAGNAT2645** [comment]
Весь набор LAMP, сайт (+ хранилище контента) и бот для Discord.

**Comment by megoRU** [comment]
у меня примерно также только еще ts3 сервер, 2 jar файла работают (бот дискорда и plesk auto-update key)

**Comment by MAGNAT2645** [comment]
Открыл для себя такую вещь: ваучер не добавляет данные в таблицу `{префикс}_admins`?
Смотрел [тут](https://github.com/SB-MaterialAdmin/Web/blob/42e5264650a5c43b18da7c6a435ddf24d1b9fc4b/web_upload/includes/sb-callback.php#L1349).
Я то ожидал увидеть админа в той таблице после активации ваучера.
Тогда как это работает?

**Comment by MAGNAT2645** [comment]
Выяснил, что `$userbank->AddAdmin` возвращает `0`. Почему такое может быть?

**Comment by MAGNAT2645** [comment]
Мда, нашёл возможную причину: [тут](https://github.com/SB-MaterialAdmin/Web/blob/42e5264650a5c43b18da7c6a435ddf24d1b9fc4b/web_upload/includes/sb-callback.php#L1321-L1329).
В таблице `_admins` у столбца `gid` нет значения по умолчанию, а `AddAdmin_pay` пытается пропихнуть пустую строку (туда, где вообще нужно указывать `int`)

**Comment by MAGNAT2645** [comment]
Закомментировал [эти](https://github.com/SB-MaterialAdmin/Web/blob/42e5264650a5c43b18da7c6a435ddf24d1b9fc4b/web_upload/includes/sb-callback.php#L1327-L1329) строчки, теперь ваучеры работают.
Просто у меня не настроены (точнее их нет) серверные группы в SourceBans (у меня пока что свои плагины регулируют права по данным из БД).
