### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Dancbeunny98** [SB-MaterialAdmin/Web#304]
![image](https://user-images.githubusercontent.com/37336183/94323701-84232480-ff9f-11ea-9265-e83f6bd12852.png)

**Comment by megoRU** [comment]
Информативно

**Comment by megoRU** [comment]
Хостинг?
vds? 
nginx?
apache?

Все ли обновы стоят?

**Comment by Dancbeunny98** [comment]
Поправил.
