### ISSUE TITLE
Не верный путь иконок

### ISSUE THREAD

**Issue by kleuser75** [SB-MaterialAdmin/Web#306]
Нашел маленькую ошибку в путях иконок в файле **/pages/admin.settings.php**

```
<img src='themes/images/admin/warning.png' alt='Warning'>
<img src='themes/images/admin/error.png' alt='Error'>
```
Надо заменить на
```
<img src='theme/images/admin/warning.png' alt='Warning'>
<img src='theme/images/admin/error.png' alt='Error'>
```

**Comment by megoRU** [comment]
confirmed

**Comment by CrazyHackGUT** [comment]
Fixed, но Вы только из мастера сейчас не раскатывайтесь. Я там шаблонизатор обновил неделю назад где-то, и ещё не всё работает, как раньше. Где-то ошибки компиляции. Решаю ещё этот вопрос.
