### ISSUE TITLE
Пропадают баны

### ISSUE THREAD

**Issue by RED4911** [SB-MaterialAdmin/Web#53]
Через некоторое время после добавление бана он пропадает со страницы, хотя по базе в таблицах,он есть. В логах добавление бана так же пропадает и не отображается, хотя отображается что был добавлен комментарий к бану.

**Comment by CrazyHackGUT** [comment]
Посмотрю. Версия 1.1.5.1?

**Comment by RED4911** [comment]
версия последняя dev

**Comment by CrazyHackGUT** [comment]
Не смог таки выявить баг. Есть возможность увидеть дамп таблицы с этими "невидимыми" банами?

**Comment by CrazyHackGUT** [comment]
Давно ничего не было по этой проблеме. Закрыто.
