### ISSUE TITLE
Updated new serverside (v0.5.6)

### ISSUE THREAD

**Issue by IIIef** [SB-MaterialAdmin/Web#79]
Добрый день, муты выдаются навсегда, хотя в настройках конфига, прописано на 60 минут. 		"BasecommTime"		"60"

**Comment by Grey-rus** [comment]
Эти муты тока выданные нативом стандартного плагина, и лучше бы логи посмотреть. И ещё у таких мутов должна быть такая причина "Muted through base commands natives"

**Comment by IIIef** [comment]
НУ так на Old_serverside_(1.5.3-1.8) все норм, стоит 60 минут и когда игроки голосуют, игрок отправляется на 60 минут в блокировку.

**Comment by IIIef** [comment]
И еще, добавьте пожалуйста в новую версию просмотр замученных игроков, а именно наказание и кем выдано оно, как в старой версии, а так вообще отлично, что можно мутить всех разом или отдельно выбранных игроков за один раз.

**Comment by CrazyHackGUT** [comment]
Всё обсуждение новой серверной части перенесено в отдельный репозиторий.
https://github.com/SB-MaterialAdmin/NewServer
