### ISSUE TITLE
[Bug] Web sends commands for old serverside

### ISSUE THREAD

**Issue by danyzinho** [SB-MaterialAdmin/Web#86]
I do not know if it was removed or if it is a mistake with me in the SB ++ version whenever I add an admin or remove it as soon as the SB writes to the database it sends a rcon command to all the ma_wb_rehashadm Servers Or SendCommand ("sm_rehash");
SendCommand ("sm_reloadadmins");
However, in this version is not applicable, these commands are being forced to put ma_wb_rehashadm in server.cfg for each time the map change takes effect.

**Comment by CrazyHackGUT** [comment]
You tried disable "Support with SourceBans plugins"? I wrote about this option in more detail [here](https://github.com/SB-MaterialAdmin/NewServer/issues/4#issuecomment-320061665).

**Comment by danyzinho** [comment]
Thank you for your help.
Can I close it? Or do I hope to solve?

**Comment by CrazyHackGUT** [comment]
You can close it, if problem solved, yes.

**Comment by CrazyHackGUT** [comment]
Problem, it seems, solved.
