### ISSUE TITLE
[REQUEST] Watch Admin | Наблюдение за Админами

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#88]
Можно взять за **основу** этот плагин:
https://forums.alliedmods.net/showthread.php?t=217670

После чего убрать лишнее (если надо)
Также там есть интерфейс даже (правда чет он косячный)
Там чет ошибка какая-то...

> Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /var/www/user281695/data/www/wadmin.starserv.ru/includes/database.include.php:25 Stack trace: #0 /var/www/user281695/data/www/wadmin.starserv.ru/includes/database.include.php(37): Database->connect() #1 /var/www/user281695/data/www/wadmin.starserv.ru/index.php(17): Database->query('SELECT * FROM `...') #2 {main} thrown in /var/www/user281695/data/www/wadmin.starserv.ru/includes/database.include.php on line 25

В БД все работает (вроде) проверил. Так то все гуд.

Для чего это нужно?
- Удобство в наблюдении за адмЕнами.
- Удобство в мониторинге времени игры / простоя админов.
Делать или нет Решай сам Крузя.
Просто тема классная. А ты ее не захотел делать. Попробуй хотя бы с полу-готовой основой :d

**Comment by BlackYuzia** [comment]
@CrazyHackGUT Призываю тебя! :D

**Comment by CrazyHackGUT** [comment]
**Муторно.** _[x2]_
Мне проще исправить косяки в этой панели, и выложить на Хлмоде.

**Comment by BlackYuzia** [comment]
@CrazyHackGUT тогди Пиздуй Пилить.

**Comment by BlackYuzia** [comment]
@CrazyHackGUT Пили короч.
