### ISSUE TITLE
Причины на выбор для разблокировки

### ISSUE THREAD

**Issue by Dreizehnt** [SB-MaterialAdmin/Web#91]
Сейчас при "разбане" нужно писать каждый раз причину, но у меня допустим всё общение на форуме и причины остаются там же, просто человек спокойно прошёл процедуру общения об этом я и сообщаю в SB. Чтобы люди просматривая списки шли на форум. Так же снимаю ошибочные баны, снимаю баны в случае попадания игрока в поле зрения - тоже две разные причины.

Выходит 3 причины у меня, которые неизменны.

Вот собственно и идея :D

**Comment by CrazyHackGUT** [comment]
Сделаю.

**Comment by CrazyHackGUT** [comment]
Сделано, потребуется прогнать апдейтер и на всякий случай все кэши JS и CSS сбросить.
