### ISSUE TITLE
[REQUEST] Time delete expire admins

### ISSUE THREAD

**Issue by BlackYuzia** [SB-MaterialAdmin/Web#92]
@CrazyHackGUT значит записывай. :D 
Добавить в WEB функцию авто удаления админов про времени. К примеру:
Удалять ли истекших админов после <N> кол. дней?

Вот. Все. Жду это в 1.1.6 :D

**Comment by BlackYuzia** [comment]
@CrazyHackGUT Блэт. Добавь ЛОГИРОВАНИЕ (хотя бы, да) входов админа на СЕРВЕРЕ (а то в веб есть а на серв нет?)

**Comment by CrazyHackGUT** [comment]
На форуме публиковалось, но под СБ от Онотоле.
По структуре таблицы админов, наш ничем не отличается,
Ничто не мешает взять тот скрипт, и запихать в крон.
Алсо, раз пишешь тайтл на английском, то и в тело обсуждения тоже пиши на англе.

**Comment by BlackYuzia** [comment]
Ебать ты быстро прикрыл лавочку. :D

**Comment by BlackYuzia** [comment]
``
, раз пишешь тайтл на английском, то и в тело обсуждения тоже пиши на англе.
```

Как 2 пальца...
