### ISSUE TITLE
Не отправляются админы с сайта на сервер

### ISSUE THREAD

**Issue by mrmaylo** [SB-MaterialAdmin/Web#93]
Создаю в веб панели админов, на сервере никаких новых записей не появляется, подскажите где рыть чтобы найти ошибку и исправить?

**Comment by CrazyHackGUT** [comment]
Смотрели [этот пост](http://hlmod.ru/posts/297763)?

**Comment by mrmaylo** [comment]
Галочку эту снял, добавьте этот совет в wiki.
Но мне он не помог. Запретить удалённое управление через RCON - разрешен.
В чем еще может быть проблема?

**Comment by CrazyHackGUT** [comment]
А RCON вообще уходит на сервер?

**Comment by mrmaylo** [comment]
При создании нового админа или удалении в панели идет отправка и пишет что успешно.

**Comment by mrmaylo** [comment]
В общем все работало, просто ожидал что записи будут появляться в админ симпл, а они в свой файл плагина админс. Спасибо за помощь!
