### ISSUE TITLE
Баг с поиском в системном логе

### ISSUE THREAD

**Issue by RaayNoff** [SB-MaterialAdmin/Web#95]
При поиске в системном логе через пункт "дата", робот говорит, что ты даун 💃 
![robot](https://user-images.githubusercontent.com/25101909/30780915-3f2722e0-a148-11e7-9208-d2a920cfb55f.PNG)

**Comment by CrazyHackGUT** [comment]
Сейчас проверю...

**Comment by CrazyHackGUT** [comment]
Исправлено. https://github.com/SB-MaterialAdmin/Web/commit/7f15ebf5d6b6cbace49df58d3bbb0de77f1a5a69
