### ISSUE TITLE
Модуль для снятия последнего бана или мута

### ISSUE THREAD

**Issue by Dreizehnt** [SB-MaterialAdmin/Web#97]
Предлагаю добавить к функционалу администратора полезную функцию для снятия **последней** блокировки выданной им. В виде модуля самый идеальный вариант.

Нередко в пылу игры нажимаются кнопки и банится игрок случайно, администратор неверно избрал меру - тоже страдает игрок, выдаётся большой мут и игрок расстраивается, выходит - для этого всего предлагаю команды в чат/консоль:
**sm_ub**, **!ub** - снимает последний бан выданный данным администратором;
**sm_um**, **!um** - снимает последний мут выданный данным администратором (здесь стоит учесть что снять нужно все муты с игрока, если возможно так сделать).

Выдачу функции предлагаю поставить на флаг разбана (**e**), а администраторам без этой функции команду запретить о чём предупреждать в чат: "_Вы не обладаете функцией снимать свои баны_" - кому надо сменить флаг, дать такую возможность, но тут стоит посмотреть что будет происходить в вебке, по идее разбан не администратором, а сервером будет с причиной, тоже неплохо. В сообщении на сайте писать: "_Ошибочный бан/мут_".
_Дополнительно. Выводить и в Discord действие, т.к. реализуется на сервере._

**В чём профит?** Не надо лезть в "вебку", можно быстро исправить ошибку и игрок не успеет среагировать и зайдёт на сервер снова.

**Comment by CrazyHackGUT** [comment]
Moved. https://github.com/SB-MaterialAdmin/OldServer/issues/18
