### ISSUE TITLE
Снятие админки

### ISSUE THREAD

**Issue by megowot** [SB-MaterialAdmin/Web#99]
Крч когда снимаешь админу (галочку с сервера) то приходиться еще 1 раз вручную писать sm_reloadadmins
Вот видео https://www.youtube.com/watch?v=ZNsMWqQf6bY

**Comment by CrazyHackGUT** [comment]
Тоже самое с выдачей. 
Проблема в слишком быстро работающем рконе. Сервер не успевает загрузить новый кеш админов в файлы, как сразу надо загружать его из файлов. 
Временное решение предлагалось [здесь](http://forum.myarena.ru/index.php?/topic/35781-alpha-material-admin-refork-sb-1547/page-24#entry313997).

**Comment by CrazyHackGUT** [comment]
Исправлено следующими коммитами:
- https://github.com/SB-MaterialAdmin/Web/commit/8d067bb18d69da331139b4b591e631a44782cfd3
- https://github.com/SB-MaterialAdmin/Web/commit/376f5e718698eb2707561dab3acf4d90b01c543f

Совсем забыл про этот "баг"...
